version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: pos_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: optimapos_db
      POSTGRES_USER: pixel
      POSTGRES_PASSWORD: pokoloko123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
