# Generated by Django 5.2.3 on 2025-07-22 09:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official company name', max_length=255, verbose_name='Company Name')),
                ('vat_number', models.CharField(blank=True, help_text='Official VAT registration number', max_length=15, verbose_name='VAT Number')),
                ('vat_registered', models.BooleanField(default=True, help_text='Is company registered for VAT? Affects entire system VAT behavior', verbose_name='VAT Registered')),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Default VAT rate for the country (Bulgaria: 20%)', max_digits=5, verbose_name='Default VAT Rate %')),
                ('address', models.TextField(blank=True, help_text='Company official address', verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('registration_number', models.CharField(blank=True, help_text='Company registration number with court', max_length=20, verbose_name='Registration Number')),
                ('vat_registration_date', models.DateField(blank=True, help_text='Date when company became VAT registered (for transition tracking)', null=True, verbose_name='VAT Registration Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
