# Generated by Django 5.2.3 on 2025-09-01 20:17

from django.db import migrations, models


def auto_detect_semantic_types(apps, schema_editor):
    """Auto-detect semantic types for existing ApprovalRule records"""
    ApprovalRule = apps.get_model('nomenclatures', 'ApprovalRule')
    
    for rule in ApprovalRule.objects.all():
        if not rule.to_status_obj:
            continue
            
        to_status = rule.to_status_obj.code.lower()
        
        # Auto-detect semantic type based on target status
        if any(word in to_status for word in ['submit', 'pending', 'review']):
            rule.semantic_type = 'submit'
        elif any(word in to_status for word in ['approv', 'complet', 'finish', 'done', 'received']):
            rule.semantic_type = 'approve'
        elif any(word in to_status for word in ['reject', 'declin', 'refus']):
            rule.semantic_type = 'reject'
        elif any(word in to_status for word in ['cancel', 'abort']):
            rule.semantic_type = 'cancel'
        elif any(word in to_status for word in ['draft', 'initial']):
            rule.semantic_type = 'return_draft'
        else:
            rule.semantic_type = 'generic'
            
        rule.save()


def reverse_semantic_types(apps, schema_editor):
    """Reset all semantic types to generic"""
    ApprovalRule = apps.get_model('nomenclatures', 'ApprovalRule')
    ApprovalRule.objects.update(semantic_type='generic')


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrule',
            name='semantic_type',
            field=models.CharField(choices=[('submit', 'Submit for Approval'), ('approve', 'Approve/Complete'), ('reject', 'Reject/Decline'), ('cancel', 'Cancel'), ('return_draft', 'Return to Draft'), ('generic', 'Generic Action')], default='generic', help_text='Semantic meaning of this transition for UI purposes', max_length=20, verbose_name='Semantic Action Type'),
        ),
        migrations.RunPython(
            auto_detect_semantic_types,
            reverse_semantic_types
        ),
    ]
