# Generated by Django 5.2.3 on 2025-07-14 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('nomenclatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poslocation',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pos_locations', to='inventory.inventorylocation', verbose_name='Location'),
            preserve_default=False,
        ),
    ]
