# Generated by Django 5.2.3 on 2025-07-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Price Group Name')),
                ('code', models.CharField(help_text='Short code for quick reference', max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('default_discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Default discount percentage for this group', max_digits=5, verbose_name='Default Discount %')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority = takes precedence in conflicts', verbose_name='Priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Price Group',
                'verbose_name_plural': 'Price Groups',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
