# Generated by Django 5.2.3 on 2025-07-12 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poslocation',
            name='default_customer',
            field=models.ForeignKey(blank=True, help_text='Default customer for anonymous sales', null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.customer'),
        ),
    ]
