# Generated by Django 5.2.3 on 2025-07-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0002_poslocation_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='POSLocation',
        ),
    ]
