# Generated by Django 5.2.3 on 2025-09-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0002_add_semantic_type_to_approval_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttypestatus',
            name='semantic_type',
            field=models.CharField(choices=[('submit', 'Submit'), ('approve', 'Approve'), ('reject', 'Reject'), ('cancel', 'Cancel'), ('return_draft', 'Return to Draft'), ('generic', 'Generic')], default='generic', help_text='Semantic type for UI action buttons and transitions', max_length=50, verbose_name='Semantic Type'),
        ),
    ]
