# Generated by Django 5.2.3 on 2025-07-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0003_documenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='auto_approve_conditions',
            field=models.JSONField(blank=True, default=dict, help_text='Conditions for automatic approval', null=True, verbose_name='Auto Approve Conditions'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='custom_validation_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Additional validation rules in JSON format', null=True, verbose_name='Custom Validation Rules'),
        ),
    ]
