# Generated by Django 5.2.3 on 2025-07-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0005_approvalrule_approvallog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='auto_transitions',
        ),
    ]
