# Generated by Django 5.2.3 on 2025-07-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0006_remove_documenttype_auto_transitions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='approval_levels',
        ),
    ]
