# Generated by Django 5.2.3 on 2025-07-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0007_remove_documenttype_approval_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='allows_anonymous',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='requires_customer',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='requires_supplier',
        ),
    ]
