# Generated by Django 5.2.3 on 2025-07-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0008_remove_documenttype_allows_anonymous_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='allowed_source_types',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='can_be_source',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='can_reference_multiple_sources',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='supports_foreign_currency',
        ),
    ]
