# Generated by Django 5.2.3 on 2025-07-20 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0009_remove_documenttype_allowed_source_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='allows_partial_delivery',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='delivery_tolerance_percent',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='handles_returns',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='reverses_original',
        ),
    ]
