# Generated by Django 5.2.3 on 2025-07-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0010_remove_documenttype_allows_partial_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='custom_validation_rules',
        ),
    ]
