# Generated by Django 5.2.3 on 2025-07-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0010_remove_documenttype_allows_partial_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documenttype',
            name='nomenclatur_require_832721_idx',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='approval_limit',
        ),


        migrations.AddIndex(
            model_name='documenttype',
            index=models.Index(fields=['requires_approval'], name='nomenclatur_require_c22004_idx'),
        ),
    ]
