# Generated by Django 5.2.3 on 2025-08-11 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0012_remove_documenttype_auto_approve_conditions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documenttype',
            name='nomenclatur_affects_0555c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='documenttype',
            name='nomenclatur_is_fisc_faaf35_idx',
        ),
        migrations.AlterUniqueTogether(
            name='documenttype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='allows_attachments',
            field=models.BooleanField(default=True, help_text='Can attach files to documents of this type', verbose_name='Allows Attachments'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='auto_create_movements',
            field=models.BooleanField(default=False, help_text='Automatically create inventory movements when document is processed', verbose_name='Auto Create Movements'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='affects_inventory',
            field=models.BooleanField(default=False, help_text='Does this document type change inventory quantities?', verbose_name='Affects Inventory'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='app_name',
            field=models.CharField(help_text='Django app: purchases, sales, inventory, hr, contracts', max_length=50, verbose_name='App Name'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='auto_number',
            field=models.BooleanField(default=True, help_text='Automatically assign document numbers (uses numbering.py configuration)', verbose_name='Auto Number'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='inventory_direction',
            field=models.CharField(choices=[('in', 'Increases Stock (IN) - deliveries, production, adjustments+'), ('out', 'Decreases Stock (OUT) - sales, consumption, adjustments-'), ('both', 'Can be Both - transfers, complex adjustments'), ('none', 'No Effect - quotes, requests, reports')], default='none', help_text='How this document affects inventory levels', max_length=10, verbose_name='Inventory Direction'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='is_fiscal',
            field=models.BooleanField(default=False, help_text='Subject to Bulgarian fiscal regulations (VAT, 10-digit numbering, NRA requirements)', verbose_name='Is Fiscal Document'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Must be approved before processing (uses ApprovalRule system)', verbose_name='Requires Approval'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='For custom ordering in lists and dropdowns', verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='type_key',
            field=models.CharField(help_text='Unique identifier: purchase_request, sales_invoice, inventory_adjustment, etc.', max_length=50, verbose_name='Type Key'),
        ),
        migrations.AddIndex(
            model_name='documenttype',
            index=models.Index(fields=['affects_inventory', 'inventory_direction'], name='nomenclatur_affects_7f4a89_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttype',
            index=models.Index(fields=['is_fiscal'], name='nomenclatur_is_fisc_03a921_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttype',
            index=models.Index(fields=['auto_create_movements'], name='nomenclatur_auto_cr_cc5303_idx'),
        ),
        migrations.AddConstraint(
            model_name='documenttype',
            constraint=models.UniqueConstraint(fields=('app_name', 'type_key'), name='unique_app_type_key'),
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='allowed_statuses',
        ),

        migrations.RemoveField(
            model_name='documenttype',
            name='auto_confirm',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='current_number',
        ),

        migrations.RemoveField(
            model_name='documenttype',
            name='default_status',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='final_statuses',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='handles_price_variances',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='inventory_timing',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='last_reset_year',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='max_total_amount',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='min_total_amount',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='number_format',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='number_prefix',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='opens_cash_drawer',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='pos_document',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='prints_receipt',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='requires_batch_tracking',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='requires_certificates',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='requires_expiry_dates',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='requires_lines',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='requires_payment',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='requires_quality_check',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='requires_serial_numbers',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='requires_vat_calculation',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='reset_numbering_yearly',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='status_transitions',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='supports_landed_cost',
        ),
    ]
