# Generated by Django 5.2.3 on 2025-08-11 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0014_locationnumberingassignment_numberingconfiguration_and_more'),
    ]

    operations = [


    ]
