# Generated by Django 5.2.3 on 2025-07-22 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0014_remove_documenttype_auto_approve_conditions_and_more'),
    ]



