# Generated by Django 5.2.3 on 2025-08-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0015_remove_documenttype_auto_approve_conditions_and_more'),
    ]

    operations = [

    ]
