# Generated by Django 5.2.3 on 2025-08-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0015_remove_documenttype_auto_approve_conditions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='auto_approve_conditions',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='custom_validation_rules',
        ),
    ]
