# Generated by Django 5.2.3 on 2025-08-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0016_remove_documenttype_auto_approve_conditions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalrule',
            name='auto_approve_conditions',
        ),
    ]
