# Generated by Django 5.2.3 on 2025-08-13 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('nomenclatures', '0018_documentstatus_documenttypestatus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='approvalrule',
            name='unique_approval_rule_per_level',
        ),
        migrations.AddConstraint(
            model_name='approvalrule',
            constraint=models.UniqueConstraint(fields=('document_type', 'from_status_obj', 'to_status_obj', 'approval_level'), name='unique_approval_rule_per_level'),
        ),
    ]
