# Generated by Django 5.2.3 on 2025-08-14 18:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('nomenclatures', '0018_documentstatus_documenttypestatus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.RemoveIndex(
            model_name='approvallog',
            name='nomenclatur_actor_i_4b772e_idx',
        ),
        migrations.RemoveIndex(
            model_name='approvallog',
            name='nomenclatur_action_eee812_idx',
        ),
        migrations.RemoveIndex(
            model_name='approvallog',
            name='nomenclatur_rule_id_ad328c_idx',
        ),
        migrations.RemoveIndex(
            model_name='approvalrule',
            name='nomenclatur_approva_4e1ec9_idx',
        ),
        migrations.RemoveField(
            model_name='approvalrule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='approvalrule',
            name='notify_on_complete',
        ),
        migrations.RemoveField(
            model_name='approvalrule',
            name='notify_on_trigger',
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='action',
            field=models.CharField(choices=[('submitted', 'Submitted for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated'), ('cancelled', 'Cancelled')], max_length=20, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.approvalrule', verbose_name='Applied Rule'),
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Browser/client user agent', verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='approvalrule',
            name='approver_permission',
            field=models.ForeignKey(blank=True, help_text='Permission required to approve (if type=permission)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='auth.permission', verbose_name='Required Permission'),
        ),
        migrations.AlterField(
            model_name='approvalrule',
            name='approver_role',
            field=models.ForeignKey(blank=True, help_text='Group/role that can approve (if type=role)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='auth.group', verbose_name='Approver Role'),
        ),
        migrations.AlterField(
            model_name='approvalrule',
            name='approver_type',
            field=models.CharField(choices=[('user', 'Specific User'), ('role', 'User Group/Role'), ('permission', 'Permission-based'), ('dynamic', 'Dynamic (determined at runtime)')], default='role', help_text='How to determine who can approve', max_length=20, verbose_name='Approver Type'),
        ),
        migrations.AlterField(
            model_name='approvalrule',
            name='approver_user',
            field=models.ForeignKey(blank=True, help_text='Specific user who can approve (if type=user)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to=settings.AUTH_USER_MODEL, verbose_name='Approver User'),
        ),
        migrations.AlterField(
            model_name='approvalrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='approvalrule',
            name='currency',
            field=models.CharField(default='BGN', help_text='Currency for amount limits (ISO code)', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='approvalrule',
            name='from_status_obj',
            field=models.ForeignKey(default=1, help_text='Starting status for this transition', on_delete=django.db.models.deletion.PROTECT, related_name='approval_rules_from', to='nomenclatures.documentstatus', verbose_name='From Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approvalrule',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum document amount (leave empty for unlimited)', max_digits=12, null=True, verbose_name='Maximum Amount'),
        ),
        migrations.AlterField(
            model_name='approvalrule',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum document amount for this rule to apply', max_digits=12, verbose_name='Minimum Amount'),
        ),
        migrations.AlterField(
            model_name='approvalrule',
            name='rejection_allowed',
            field=models.BooleanField(default=True, help_text='Can user reject at this level?', verbose_name='Rejection Allowed'),
        ),
        migrations.AlterField(
            model_name='approvalrule',
            name='requires_reason',
            field=models.BooleanField(default=False, help_text='Must user provide a reason/comment when using this rule?', verbose_name='Requires Reason'),
        ),
        migrations.AlterField(
            model_name='approvalrule',
            name='to_status_obj',
            field=models.ForeignKey(default=1, help_text='Target status for this transition', on_delete=django.db.models.deletion.PROTECT, related_name='approval_rules_to', to='nomenclatures.documentstatus', verbose_name='To Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approvalrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='approvallog',
            index=models.Index(fields=['timestamp'], name='nomenclatur_timesta_41da37_idx'),
        ),
        migrations.AddIndex(
            model_name='approvallog',
            index=models.Index(fields=['action'], name='nomenclatur_action_626322_idx'),
        ),
        migrations.AddIndex(
            model_name='approvallog',
            index=models.Index(fields=['actor'], name='nomenclatur_actor_i_f8cf55_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrule',
            index=models.Index(fields=['document_type', 'is_active'], name='nomenclatur_documen_d18334_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrule',
            index=models.Index(fields=['approval_level'], name='nomenclatur_approva_2c7607_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalrule',
            constraint=models.UniqueConstraint(fields=('document_type', 'from_status_obj', 'to_status_obj', 'approval_level'), name='unique_approval_rule_per_level'),
        ),
    ]
