# Generated by Django 5.2.3 on 2025-08-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0019_remove_approvalrule_unique_approval_rule_per_level_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='approvalrule',
            name='unique_approval_rule_per_level',
        ),
        migrations.AddField(
            model_name='documenttypestatus',
            name='allows_movement_correction',
            field=models.BooleanField(default=False, help_text='Can inventory movements be corrected when document is in this status?', verbose_name='Allows Movement Correction'),
        ),
        migrations.AddField(
            model_name='documenttypestatus',
            name='auto_correct_movements_on_edit',
            field=models.BooleanField(default=False, help_text='Automatically sync movements when document content is edited in this status?', verbose_name='Auto Correct Movements on Edit'),
        ),
        migrations.AddField(
            model_name='documenttypestatus',
            name='creates_inventory_movements',
            field=models.BooleanField(default=False, help_text='Should inventory movements be created when document enters this status?', verbose_name='Creates Inventory Movements'),
        ),
        migrations.AddField(
            model_name='documenttypestatus',
            name='reverses_inventory_movements',
            field=models.BooleanField(default=False, help_text='Should existing inventory movements be reversed when document enters this status?', verbose_name='Reverses Inventory Movements'),
        ),
    ]
