# Generated by Django 5.2.3 on 2025-08-14 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('nomenclatures', '0020_remove_approvalrule_unique_approval_rule_per_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentstatus',
            name='allows_deletion',
            field=models.BooleanField(default=False, help_text='Can documents be deleted in this status? (overrides DocumentStatus.allow_delete)', verbose_name='Allows Deletion'),
        ),
        migrations.AddField(
            model_name='documentstatus',
            name='allows_editing',
            field=models.BooleanField(default=True, help_text='Can documents be edited in this status? (overrides DocumentStatus.allow_edit)', verbose_name='Allows Editing'),
        ),
        migrations.AddConstraint(
            model_name='approvalrule',
            constraint=models.UniqueConstraint(fields=('document_type', 'from_status_obj', 'to_status_obj', 'approval_level'), name='unique_approval_rule_per_level'),
        ),
    ]
