# Generated by Django 5.2.3 on 2025-08-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0021_documentstatus_allows_deletion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentstatus',
            name='allows_deletion',
        ),
        migrations.RemoveField(
            model_name='documentstatus',
            name='allows_editing',
        ),
        migrations.AddField(
            model_name='documenttypestatus',
            name='allows_deletion',
            field=models.BooleanField(default=False, help_text='Can documents be deleted in this status? (overrides DocumentStatus.allow_delete)', verbose_name='Allows Deletion'),
        ),
        migrations.AddField(
            model_name='documenttypestatus',
            name='allows_editing',
            field=models.BooleanField(default=True, help_text='Can documents be edited in this status? (overrides DocumentStatus.allow_edit)', verbose_name='Allows Editing'),
        ),
    ]
