# Generated by Django 5.2.3 on 2025-08-20 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0022_remove_documentstatus_allows_deletion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationnumberingassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='numbering_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
    ]
