# Generated by Django 5.2.3 on 2025-08-21 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nomenclatures', '0023_convert_to_generic_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationnumberingassignment',
            options={'ordering': ['location_content_type', 'location_object_id', 'numbering_config'], 'verbose_name': 'Location Numbering Assignment', 'verbose_name_plural': 'Location Numbering Assignments'},
        ),
        migrations.RemoveConstraint(
            model_name='locationnumberingassignment',
            name='unique_location_numbering',
        ),
        migrations.RemoveIndex(
            model_name='locationnumberingassignment',
            name='nomenclatur_locatio_ed2928_idx',
        ),
        migrations.RemoveField(
            model_name='locationnumberingassignment',
            name='location',
        ),
        migrations.AddField(
            model_name='locationnumberingassignment',
            name='location_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'inventory'), ('model', 'inventorylocation')), models.Q(('app_label', 'sales'), ('model', 'onlinestore')), models.Q(('app_label', 'partners'), ('model', 'customersite')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Location Type'),
        ),
        migrations.AddField(
            model_name='locationnumberingassignment',
            name='location_object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Location ID'),
        ),
        migrations.AddIndex(
            model_name='locationnumberingassignment',
            index=models.Index(fields=['location_content_type', 'location_object_id', 'is_active'], name='nomenclatur_locatio_99f66f_idx'),
        ),
        migrations.AddConstraint(
            model_name='locationnumberingassignment',
            constraint=models.UniqueConstraint(fields=('location_content_type', 'location_object_id', 'numbering_config'), name='unique_location_numbering'),
        ),
    ]
