# Generated by Django 5.2.3 on 2025-08-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0025_documenttype_auto_receive'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documenttype',
            name='nomenclatur_auto_cr_cc5303_idx',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='auto_create_movements',
        ),
    ]
