# Generated by Django 5.2.3 on 2025-08-25 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nomenclatures', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Location ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for the entire packaging unit', max_digits=10, verbose_name='Packaging Price')),
                ('pricing_method', models.CharField(choices=[('FIXED', 'Fixed Price'), ('MARKUP', 'Markup on Base Unit'), ('AUTO', 'Auto (from base unit price)')], default='FIXED', max_length=20, verbose_name='Pricing Method')),
                ('markup_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Markup % over base unit price', max_digits=5, null=True, verbose_name='Markup Percentage')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Discount % from calculated base price', max_digits=5, verbose_name='Discount Percentage')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Location Type')),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_prices', to='products.productpackaging', verbose_name='Packaging')),
            ],
            options={
                'verbose_name': 'Packaging Price',
                'verbose_name_plural': 'Packaging Prices',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='pricing_pac_content_db5438_idx'), models.Index(fields=['packaging', 'is_active'], name='pricing_pac_packagi_ef14e1_idx')],
                'unique_together': {('content_type', 'object_id', 'packaging')},
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Location ID')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed base selling price', max_digits=10, null=True, verbose_name='Base Price')),
                ('markup_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Markup % over cost price', max_digits=5, null=True, verbose_name='Markup Percentage')),
                ('effective_price', models.DecimalField(decimal_places=2, default=0, help_text='Calculated effective selling price', max_digits=10, verbose_name='Effective Price')),
                ('pricing_method', models.CharField(choices=[('FIXED', 'Fixed Price'), ('MARKUP', 'Markup on Cost'), ('AUTO', 'Auto (Location Default)')], default='FIXED', max_length=20, verbose_name='Pricing Method')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('last_cost_update', models.DateTimeField(blank=True, null=True, verbose_name='Last Cost Update')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'inventory'), ('model', 'inventorylocation')), models.Q(('app_label', 'sales'), ('model', 'onlinestore')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Location Type')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_prices', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Price',
                'verbose_name_plural': 'Product Prices',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='pricing_pro_content_8d1d6a_idx'), models.Index(fields=['product', 'is_active'], name='pricing_pro_product_5d4d20_idx'), models.Index(fields=['pricing_method'], name='pricing_pro_pricing_0da5a5_idx')],
                'unique_together': {('content_type', 'object_id', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ProductPriceByGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Location ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Special price for this group', max_digits=10, verbose_name='Group Price')),
                ('min_quantity', models.DecimalField(decimal_places=3, default=1, help_text='Minimum quantity to get this price', max_digits=10, verbose_name='Minimum Quantity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Location Type')),
                ('price_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_group_prices', to='nomenclatures.pricegroup', verbose_name='Price Group')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_prices', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Price by Group',
                'verbose_name_plural': 'Product Prices by Group',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='pricing_pro_content_443086_idx'), models.Index(fields=['product', 'price_group'], name='pricing_pro_product_d982f5_idx')],
                'unique_together': {('content_type', 'object_id', 'product', 'price_group', 'min_quantity')},
            },
        ),
        migrations.CreateModel(
            name='ProductStepPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Location ID')),
                ('min_quantity', models.DecimalField(decimal_places=3, help_text='Minimum quantity to get this price', max_digits=10, verbose_name='Minimum Quantity')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this quantity step', max_digits=10, verbose_name='Step Price')),
                ('description', models.CharField(blank=True, help_text='Optional description for this price step', max_length=100, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Location Type')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_prices', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Step Price',
                'verbose_name_plural': 'Product Step Prices',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='pricing_pro_content_2ef5dc_idx'), models.Index(fields=['product', 'min_quantity'], name='pricing_pro_product_266dee_idx')],
                'unique_together': {('content_type', 'object_id', 'product', 'min_quantity')},
            },
        ),
        migrations.CreateModel(
            name='PromotionalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Location ID')),
                ('name', models.CharField(help_text='Descriptive name for this promotion', max_length=100, verbose_name='Promotion Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the promotion', verbose_name='Description')),
                ('promotional_price', models.DecimalField(decimal_places=2, help_text='Special promotional price', max_digits=10, verbose_name='Promotional Price')),
                ('start_date', models.DateField(help_text='When the promotion becomes active', verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='When the promotion expires', verbose_name='End Date')),
                ('min_quantity', models.DecimalField(decimal_places=3, default=1, help_text='Minimum quantity to get promotional price', max_digits=10, verbose_name='Minimum Quantity')),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Maximum quantity per transaction (optional)', max_digits=10, null=True, verbose_name='Maximum Quantity')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority takes precedence when promotions overlap', verbose_name='Priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Location Type')),
                ('customer_groups', models.ManyToManyField(blank=True, help_text='Limit promotion to specific customer groups (leave empty for all)', related_name='promotions', to='nomenclatures.pricegroup', verbose_name='Customer Groups')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotional_prices', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Promotional Price',
                'verbose_name_plural': 'Promotional Prices',
                'ordering': ['-priority', 'start_date'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='pricing_pro_content_0f418b_idx'), models.Index(fields=['start_date', 'end_date'], name='pricing_pro_start_d_0ef7e8_idx'), models.Index(fields=['product', 'start_date'], name='pricing_pro_product_154e08_idx')],
            },
        ),
    ]
