# Generated by Django 5.2.3 on 2025-08-20 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nomenclatures', '0023_convert_to_generic_fk'),
        ('pricing', '0001_initial'),
        ('products', '0002_remove_product_current_avg_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagingprice',
            options={'verbose_name': 'Packaging Price', 'verbose_name_plural': 'Packaging Prices'},
        ),
        migrations.AlterModelOptions(
            name='productprice',
            options={'verbose_name': 'Product Price', 'verbose_name_plural': 'Product Prices'},
        ),
        migrations.AlterModelOptions(
            name='productpricebygroup',
            options={'verbose_name': 'Product Price by Group', 'verbose_name_plural': 'Product Prices by Group'},
        ),
        migrations.AlterModelOptions(
            name='productstepprice',
            options={'verbose_name': 'Product Step Price', 'verbose_name_plural': 'Product Step Prices'},
        ),
        migrations.AlterModelOptions(
            name='promotionalprice',
            options={'ordering': ['-priority', 'start_date'], 'verbose_name': 'Promotional Price', 'verbose_name_plural': 'Promotional Prices'},
        ),
        migrations.RemoveIndex(
            model_name='promotionalprice',
            name='pricing_pro_locatio_349c9c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='packagingprice',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productpricebygroup',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productstepprice',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='promotionalprice',
            name='location',
        ),
        migrations.AddField(
            model_name='packagingprice',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Location Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagingprice',
            name='object_id',
            field=models.PositiveIntegerField(default=1, verbose_name='Location ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productprice',
            name='content_type',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(models.Q(('app_label', 'inventory'), ('model', 'inventorylocation')), models.Q(('app_label', 'sales'), ('model', 'onlinestore')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Location Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productprice',
            name='object_id',
            field=models.PositiveIntegerField(default=1, verbose_name='Location ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpricebygroup',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Location Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpricebygroup',
            name='object_id',
            field=models.PositiveIntegerField(default=1, verbose_name='Location ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productstepprice',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Location Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productstepprice',
            name='object_id',
            field=models.PositiveIntegerField(default=1, verbose_name='Location ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotionalprice',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Location Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotionalprice',
            name='object_id',
            field=models.PositiveIntegerField(default=1, verbose_name='Location ID'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='packagingprice',
            index=models.Index(fields=['content_type', 'object_id'], name='pricing_pac_content_db5438_idx'),
        ),
        migrations.AddIndex(
            model_name='packagingprice',
            index=models.Index(fields=['packaging', 'is_active'], name='pricing_pac_packagi_ef14e1_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['content_type', 'object_id'], name='pricing_pro_content_8d1d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['product', 'is_active'], name='pricing_pro_product_5d4d20_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['pricing_method'], name='pricing_pro_pricing_0da5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='productpricebygroup',
            index=models.Index(fields=['content_type', 'object_id'], name='pricing_pro_content_443086_idx'),
        ),
        migrations.AddIndex(
            model_name='productpricebygroup',
            index=models.Index(fields=['product', 'price_group'], name='pricing_pro_product_d982f5_idx'),
        ),
        migrations.AddIndex(
            model_name='productstepprice',
            index=models.Index(fields=['content_type', 'object_id'], name='pricing_pro_content_2ef5dc_idx'),
        ),
        migrations.AddIndex(
            model_name='productstepprice',
            index=models.Index(fields=['product', 'min_quantity'], name='pricing_pro_product_266dee_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionalprice',
            index=models.Index(fields=['content_type', 'object_id'], name='pricing_pro_content_0f418b_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionalprice',
            index=models.Index(fields=['product', 'start_date'], name='pricing_pro_product_154e08_idx'),
        ),
        migrations.RemoveField(
            model_name='packagingprice',
            name='location',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='location',
        ),
        migrations.RemoveField(
            model_name='productpricebygroup',
            name='location',
        ),
        migrations.RemoveField(
            model_name='productstepprice',
            name='location',
        ),
    ]
