# Generated by Django 5.2.3 on 2025-08-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nomenclatures', '0023_convert_to_generic_fk'),
        ('pricing', '0002_alter_packagingprice_options_and_more'),
        ('products', '0002_remove_product_current_avg_cost_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='packagingprice',
            unique_together={('content_type', 'object_id', 'packaging')},
        ),
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together={('content_type', 'object_id', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='productpricebygroup',
            unique_together={('content_type', 'object_id', 'product', 'price_group', 'min_quantity')},
        ),
        migrations.AlterUniqueTogether(
            name='productstepprice',
            unique_together={('content_type', 'object_id', 'product', 'min_quantity')},
        ),
    ]
