# Generated by Django 5.2.3 on 2025-07-15 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('vat_number', models.CharField(blank=True, max_length=20, verbose_name='VAT/BULSTAT')),
                ('vat_registered', models.BooleanField(default=False, verbose_name='VAT Registered')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Contact Person')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('bank', models.CharField(blank=True, max_length=100, verbose_name='Bank')),
                ('bank_account', models.CharField(blank=True, max_length=100, verbose_name='Bank Account')),
                ('division', models.CharField(blank=True, help_text='Primary business division', max_length=100, verbose_name='Main Division')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal company supplier', verbose_name='Internal Supplier')),
                ('payment_days', models.PositiveSmallIntegerField(default=30, help_text='Standard payment terms in days', verbose_name='Payment Terms (days)')),
                ('delivery_blocked', models.BooleanField(default=False, help_text='Temporarily block deliveries from this supplier', verbose_name='Delivery Blocked')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Maximum unpaid amount allowed', max_digits=12, verbose_name='Credit Limit')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('vat_number', models.CharField(blank=True, max_length=20, verbose_name='VAT/BULSTAT')),
                ('vat_registered', models.BooleanField(default=False, verbose_name='VAT Registered')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Contact Person')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('type', models.CharField(choices=[('company', 'Company'), ('person', 'Individual')], default='company', max_length=10, verbose_name='Customer Type')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Maximum credit allowed', max_digits=12, verbose_name='Credit Limit')),
                ('payment_delay_days', models.PositiveSmallIntegerField(default=0, help_text='Days of deferred payment allowed', verbose_name='Payment Delay (days)')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Applied when no price group is set', max_digits=5, null=True, verbose_name='Default Discount %')),
                ('category', models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('problematic', 'Problematic')], default='regular', max_length=20, verbose_name='Category')),
                ('sales_blocked', models.BooleanField(default=False, help_text='Block all sales to this customer', verbose_name='Sales Blocked')),
                ('credit_blocked', models.BooleanField(default=False, help_text='Block credit sales, cash only', verbose_name='Credit Blocked')),
                ('price_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.pricegroup', verbose_name='Price Group')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3, verbose_name='Day')),
                ('expects_order', models.BooleanField(default=False, help_text='Does customer place orders on this day?', verbose_name='Places Orders')),
                ('expects_delivery', models.BooleanField(default=False, help_text='Does customer expect deliveries on this day?', verbose_name='Expects Delivery')),
                ('preferred_delivery_time_from', models.TimeField(blank=True, null=True, verbose_name='Preferred Delivery From')),
                ('preferred_delivery_time_to', models.TimeField(blank=True, null=True, verbose_name='Preferred Delivery To')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_schedules', to='partners.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Customer Day Schedule',
                'verbose_name_plural': 'Customer Day Schedules',
                'ordering': ['customer', 'day'],
                'unique_together': {('customer', 'day')},
            },
        ),
        migrations.CreateModel(
            name='CustomerSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Site Name')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Contact Person')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_delivery_address', models.BooleanField(default=True, verbose_name='Delivery Address')),
                ('is_billing_address', models.BooleanField(default=False, verbose_name='Billing Address')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Site')),
                ('special_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Special Discount %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='partners.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Customer Site',
                'verbose_name_plural': 'Customer Sites',
                'ordering': ['customer', 'name'],
                'unique_together': {('customer', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SupplierDaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3, verbose_name='Day')),
                ('expects_order', models.BooleanField(default=False, help_text='Does supplier expect orders on this day?', verbose_name='Expects Order')),
                ('makes_delivery', models.BooleanField(default=False, help_text='Does supplier make deliveries on this day?', verbose_name='Makes Delivery')),
                ('order_deadline_time', models.TimeField(blank=True, help_text='Latest time to place orders for this day', null=True, verbose_name='Order Deadline')),
                ('delivery_time_from', models.TimeField(blank=True, null=True, verbose_name='Delivery From')),
                ('delivery_time_to', models.TimeField(blank=True, null=True, verbose_name='Delivery To')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_schedules', to='partners.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Supplier Day Schedule',
                'verbose_name_plural': 'Supplier Day Schedules',
                'ordering': ['supplier', 'day'],
                'unique_together': {('supplier', 'day')},
            },
        ),
        migrations.CreateModel(
            name='SupplierDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Division Name')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Division Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Contact Person')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('payment_days', models.PositiveSmallIntegerField(blank=True, help_text='Override supplier payment terms for this division', null=True, verbose_name='Payment Terms (days)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='partners.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Supplier Division',
                'verbose_name_plural': 'Supplier Divisions',
                'ordering': ['supplier', 'name'],
                'unique_together': {('supplier', 'name')},
            },
        ),
    ]
