# Generated by Django 5.2.3 on 2025-07-12 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('pricing', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='price_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.pricegroup', verbose_name='Price Group'),
        ),
    ]
