# Generated by Django 5.2.3 on 2025-07-16 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0002_pricegroup'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='price_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='nomenclatures.pricegroup', verbose_name='Price Group'),
        ),
    ]
