# Generated by Django 5.2.3 on 2025-08-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_customer_price_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.CharField(default=1, help_text='Short unique code for this partner (e.g. ABC, PIXEL)', max_length=20, unique=True, verbose_name='Partner Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='code',
            field=models.CharField(default=1, help_text='Short unique code for this partner (e.g. ABC, PIXEL)', max_length=20, unique=True, verbose_name='Partner Code'),
            preserve_default=False,
        ),
    ]
