# Generated by Django 5.2.3 on 2025-07-13 09:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorymovement_purchase_document'),
        ('nomenclatures', '0003_poslocation_location'),
        ('partners', '0002_customer_price_group'),
        ('products', '0001_initial'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('confirm', 'Confirmed'), ('receive', 'Received'), ('cancel', 'Cancelled'), ('price_update', 'Price Updated')], max_length=20, verbose_name='Action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('field_name', models.CharField(blank=True, max_length=50, verbose_name='Field Name')),
                ('old_value', models.TextField(blank=True, verbose_name='Old Value')),
                ('new_value', models.TextField(blank=True, verbose_name='New Value')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Purchase Audit Log',
                'verbose_name_plural': 'Purchase Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['type_key', 'code'], 'verbose_name': 'Document Type', 'verbose_name_plural': 'Document Types'},
        ),
        migrations.AlterModelOptions(
            name='purchasedocument',
            options={'ordering': ['-delivery_date', '-document_date'], 'verbose_name': 'Purchase Document', 'verbose_name_plural': 'Purchase Documents'},
        ),
        migrations.AlterModelOptions(
            name='purchasedocumentline',
            options={'ordering': ['document', 'line_number'], 'verbose_name': 'Purchase Document Line', 'verbose_name_plural': 'Purchase Document Lines'},
        ),
        migrations.RemoveField(
            model_name='purchasedocument',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='purchasedocument',
            name='prices_include_vat',
        ),
        migrations.RemoveField(
            model_name='purchasedocument',
            name='total_after_discount',
        ),
        migrations.RemoveField(
            model_name='purchasedocument',
            name='total_before_discount',
        ),
        migrations.RemoveField(
            model_name='purchasedocument',
            name='total_discount',
        ),
        migrations.RemoveField(
            model_name='purchasedocument',
            name='total_vat',
        ),
        migrations.RemoveField(
            model_name='purchasedocumentline',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='purchasedocumentline',
            name='suggested_sale_price',
        ),
        migrations.AddField(
            model_name='documenttype',
            name='auto_confirm',
            field=models.BooleanField(default=False, help_text='Automatically confirm document on creation', verbose_name='Auto Confirm'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='auto_receive',
            field=models.BooleanField(default=False, help_text='Automatically receive document on confirmation', verbose_name='Auto Receive'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documenttype',
            name='requires_expiry',
            field=models.BooleanField(default=False, help_text='Whether expiry dates are mandatory', verbose_name='Requires Expiry Date'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='external_reference',
            field=models.CharField(blank=True, help_text='PO number, contract reference, etc.', max_length=100, verbose_name='External Reference'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Date'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='supplier_document_number',
            field=models.CharField(blank=True, help_text="Supplier's invoice/delivery note number", max_length=50, verbose_name='Supplier Document Number'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_documents', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='VAT Amount'),
        ),
        migrations.AddField(
            model_name='purchasedocumentline',
            name='quality_approved',
            field=models.BooleanField(default=True, help_text='Whether the received goods passed quality control', verbose_name='Quality Approved'),
        ),
        migrations.AddField(
            model_name='purchasedocumentline',
            name='quality_notes',
            field=models.TextField(blank=True, help_text='Notes about quality issues or inspections', verbose_name='Quality Notes'),
        ),
        migrations.AddField(
            model_name='purchasedocumentline',
            name='received_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Actually received quantity (may differ from ordered)', max_digits=10, verbose_name='Received Quantity'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='code',
            field=models.CharField(help_text='Unique code like INV, DEL, ADJ', max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='requires_batch',
            field=models.BooleanField(default=False, help_text='Whether batch numbers are mandatory', verbose_name='Requires Batch'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='stock_effect',
            field=models.IntegerField(choices=[(1, 'Increases stock'), (-1, 'Decreases stock'), (0, 'No effect')], default=1, help_text='How this document type affects inventory levels', verbose_name='Stock Effect'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='type_key',
            field=models.CharField(choices=[('stock_in', 'Stock In (+)'), ('stock_out', 'Stock Out (-)'), ('invoice', 'Invoice'), ('transfer', 'Internal Transfer'), ('adjustment', 'Stock Adjustment')], max_length=20, verbose_name='Type Key'),
        ),
        migrations.AlterField(
            model_name='purchasedocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_documents', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='purchasedocument',
            name='delivery_date',
            field=models.DateField(help_text='When goods were/will be delivered', verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='purchasedocument',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_documents', to='inventory.inventorylocation', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='purchasedocument',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_documents', to='partners.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='purchasedocumentline',
            name='batch_number',
            field=models.CharField(blank=True, default=1, max_length=50, verbose_name='Batch Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasedocumentline',
            name='final_unit_price',
            field=models.DecimalField(decimal_places=4, help_text='Unit price after discount', max_digits=10, verbose_name='Final Unit Price'),
        ),
        migrations.AlterField(
            model_name='purchasedocumentline',
            name='line_number',
            field=models.PositiveSmallIntegerField(verbose_name='Line Number'),
        ),
        migrations.AlterField(
            model_name='purchasedocumentline',
            name='line_total',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Line Total'),
        ),
        migrations.AlterField(
            model_name='purchasedocumentline',
            name='markup_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated markup percentage', max_digits=7, null=True, verbose_name='Markup Percentage'),
        ),
        migrations.AlterField(
            model_name='purchasedocumentline',
            name='new_sale_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Suggested selling price based on purchase cost', max_digits=10, null=True, verbose_name='Suggested Sale Price'),
        ),
        migrations.AlterField(
            model_name='purchasedocumentline',
            name='old_sale_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Current selling price before this purchase', max_digits=10, null=True, verbose_name='Current Sale Price'),
        ),
        migrations.AlterField(
            model_name='purchasedocumentline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='purchasedocumentline',
            name='quantity_base_unit',
            field=models.DecimalField(decimal_places=3, help_text='Automatically calculated', max_digits=10, verbose_name='Quantity (Base Unit)'),
        ),
        migrations.AlterField(
            model_name='purchasedocumentline',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='purchasedocumentline',
            name='unit_price_base',
            field=models.DecimalField(decimal_places=4, help_text='Price per base unit - automatically calculated', max_digits=10, verbose_name='Unit Price (Base)'),
        ),
        migrations.AlterField(
            model_name='purchasedocumentline',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='VAT Amount'),
        ),
        migrations.AddIndex(
            model_name='purchasedocument',
            index=models.Index(fields=['supplier', 'delivery_date'], name='purchases_p_supplie_a7afbd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedocument',
            index=models.Index(fields=['location', 'document_date'], name='purchases_p_locatio_973b44_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedocument',
            index=models.Index(fields=['status', 'delivery_date'], name='purchases_p_status_d704a4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedocumentline',
            index=models.Index(fields=['document', 'line_number'], name='purchases_p_documen_2600d9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedocumentline',
            index=models.Index(fields=['product', 'document'], name='purchases_p_product_1db415_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedocumentline',
            index=models.Index(fields=['batch_number'], name='purchases_p_batch_n_df277e_idx'),
        ),
        migrations.AddField(
            model_name='purchaseauditlog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='purchases.purchasedocument', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='purchaseauditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='purchaseauditlog',
            index=models.Index(fields=['document', '-timestamp'], name='purchases_p_documen_887252_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseauditlog',
            index=models.Index(fields=['user', '-timestamp'], name='purchases_p_user_id_17af2a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseauditlog',
            index=models.Index(fields=['action', '-timestamp'], name='purchases_p_action_cec26a_idx'),
        ),
    ]
