# Generated by Django 5.2.3 on 2025-08-28 14:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestline',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount', max_digits=10, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage', max_digits=5, verbose_name='Discount %'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='entered_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price as entered by user (may include VAT)', max_digits=10, null=True, verbose_name='Entered Price'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line amount including VAT', max_digits=12, verbose_name='Gross Amount'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line amount excluding VAT', max_digits=12, verbose_name='Net Amount'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit price WITHOUT VAT (stored value)', max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='unit_price_with_vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit price INCLUDING VAT (calculated)', max_digits=10, verbose_name='Unit Price with VAT'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT amount for this line', max_digits=10, verbose_name='VAT Amount'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='vat_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.200'), help_text='VAT rate (0.20 = 20%)', max_digits=5, verbose_name='VAT Rate'),
        ),
    ]
