# Generated by Django 5.2.3 on 2025-07-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentType',
        ),
    ]
