# Generated by Django 5.2.3 on 2025-08-30 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0001_initial'),
        ('purchases', '0002_purchaserequestline_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryline',
            name='received_quantity',
            field=models.DecimalField(decimal_places=3, help_text='Actual quantity received from supplier (quantity precision)', max_digits=12, verbose_name='Received Quantity'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='unit',
            field=models.ForeignKey(help_text='Unit in which quantity is measured (piece, box, kg, etc.)', on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.unitofmeasure', verbose_name='Unit of Measure'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='ordered_quantity',
            field=models.DecimalField(decimal_places=3, help_text='Quantity ordered from supplier (quantity precision)', max_digits=12, verbose_name='Ordered Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit',
            field=models.ForeignKey(help_text='Unit in which quantity is measured (piece, box, kg, etc.)', on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.unitofmeasure', verbose_name='Unit of Measure'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated unit price for budgeting (currency precision)', max_digits=12, null=True, verbose_name='Estimated Price'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='requested_quantity',
            field=models.DecimalField(decimal_places=3, help_text='Quantity requested in specified unit (quantity precision)', max_digits=12, verbose_name='Requested Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='unit',
            field=models.ForeignKey(help_text='Unit in which quantity is measured (piece, box, kg, etc.)', on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.unitofmeasure', verbose_name='Unit of Measure'),
        ),
    ]
