# Generated by Django 5.2.3 on 2025-07-13 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorymovement_purchase_document'),
        ('partners', '0002_customer_price_group'),
        ('purchases', '0002_purchaseauditlog_alter_documenttype_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedocument',
            name='auto_create_invoice',
            field=models.BooleanField(default=False, help_text='Automatically create invoice document when saving', verbose_name='Auto Create Invoice'),
        ),
        migrations.AddIndex(
            model_name='purchasedocument',
            index=models.Index(fields=['supplier_document_number'], name='purchases_p_supplie_6f7efa_idx'),
        ),
    ]
