# Generated by Django 5.2.3 on 2025-07-17 09:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0003_documenttype'),
        ('purchases', '0002_delete_documenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryline',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated discount amount', max_digits=10, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='serial_numbers',
            field=models.TextField(blank=True, help_text='Serial numbers (one per line)', verbose_name='Serial Numbers'),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated VAT amount', max_digits=10, verbose_name='VAT Amount'),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='VAT rate percentage', max_digits=5, verbose_name='VAT Rate %'),
        ),
        migrations.AddField(
            model_name='deliveryreceipt',
            name='document_type',
            field=models.ForeignKey(default=1, help_text='Type defines workflow, numbering and business rules', limit_choices_to={'app_name': 'purchases', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.documenttype', verbose_name='Document Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='document_type',
            field=models.ForeignKey(default=1, help_text='Type defines workflow, numbering and business rules', limit_choices_to={'app_name': 'purchases', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.documenttype', verbose_name='Document Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Batch/Lot number for tracking', max_length=50, verbose_name='Batch Number'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated discount amount', max_digits=10, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Product expiry date', null=True, verbose_name='Expiry Date'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='quality_approved',
            field=models.BooleanField(default=True, help_text='Passed quality control', verbose_name='Quality Approved'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='quality_notes',
            field=models.TextField(blank=True, help_text='Quality control notes', verbose_name='Quality Notes'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='serial_numbers',
            field=models.TextField(blank=True, help_text='Serial numbers (one per line)', verbose_name='Serial Numbers'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated VAT amount', max_digits=10, verbose_name='VAT Amount'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='VAT rate percentage', max_digits=5, verbose_name='VAT Rate %'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='document_type',
            field=models.ForeignKey(default=1, help_text='Type defines workflow, numbering and business rules', limit_choices_to={'app_name': 'purchases', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.documenttype', verbose_name='Document Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Batch/Lot number for tracking', max_length=50, verbose_name='Batch Number'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Product expiry date', null=True, verbose_name='Expiry Date'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='quality_approved',
            field=models.BooleanField(default=True, help_text='Passed quality control', verbose_name='Quality Approved'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='serial_numbers',
            field=models.TextField(blank=True, help_text='Serial numbers (one per line)', verbose_name='Serial Numbers'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total including VAT', max_digits=12, verbose_name='Line Total'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Price per unit excluding VAT', max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='document_number',
            field=models.CharField(help_text='Auto-generated from document type configuration', max_length=50, unique=True, verbose_name='Document Number'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='status',
            field=models.CharField(max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='document_number',
            field=models.CharField(help_text='Auto-generated from document type configuration', max_length=50, unique=True, verbose_name='Document Number'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total including VAT', max_digits=12, verbose_name='Line Total'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Price per unit excluding VAT', max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='document_number',
            field=models.CharField(help_text='Auto-generated from document type configuration', max_length=50, unique=True, verbose_name='Document Number'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(max_length=20, verbose_name='Status'),
        ),
    ]
