# Generated by Django 5.2.3 on 2025-07-14 12:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorymovement_purchase_document'),
        ('nomenclatures', '0003_poslocation_location'),
        ('partners', '0002_customer_price_group'),
        ('products', '0001_initial'),
        ('purchases', '0003_purchasedocument_auto_create_invoice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='purchasedocument',
            name='purchases_p_supplie_a7afbd_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchasedocument',
            name='purchases_p_status_d704a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchasedocument',
            name='purchases_p_supplie_6f7efa_idx',
        ),
        migrations.RemoveField(
            model_name='purchaseauditlog',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='purchaseauditlog',
            name='new_value',
        ),
        migrations.RemoveField(
            model_name='purchaseauditlog',
            name='old_value',
        ),
        migrations.RemoveField(
            model_name='purchasedocument',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='purchasedocument',
            name='vat_amount',
        ),
        migrations.AddField(
            model_name='documenttype',
            name='can_be_source',
            field=models.BooleanField(default=False, help_text='Whether this document type can be source for other documents', verbose_name='Can Be Source'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='can_reference_multiple_sources',
            field=models.BooleanField(default=False, help_text='Whether this document can be created from multiple source documents', verbose_name='Can Reference Multiple Sources'),
        ),
        migrations.AddField(
            model_name='purchaseauditlog',
            name='additional_data',
            field=models.JSONField(blank=True, help_text='Additional data related to the action', null=True, verbose_name='Additional Data'),
        ),
        migrations.AddField(
            model_name='purchaseauditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='purchaseauditlog',
            name='new_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='New Status'),
        ),
        migrations.AddField(
            model_name='purchaseauditlog',
            name='new_workflow_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='New Workflow Status'),
        ),
        migrations.AddField(
            model_name='purchaseauditlog',
            name='old_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='Old Status'),
        ),
        migrations.AddField(
            model_name='purchaseauditlog',
            name='old_workflow_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='Old Workflow Status'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the request was approved', null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Manager who approved the request', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Discount'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='expected_delivery_date',
            field=models.DateField(blank=True, help_text='When we expect to receive this order', null=True, verbose_name='Expected Delivery Date'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='order_reference',
            field=models.CharField(blank=True, help_text='Internal order reference or PO number', max_length=100, verbose_name='Order Reference'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='User who created the request', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested By'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='source_document',
            field=models.ForeignKey(blank=True, help_text='Reference to the document this was created from (REQ→ORD workflow)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_documents', to='purchases.purchasedocument', verbose_name='Source Document'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='supplier_confirmed',
            field=models.BooleanField(default=False, help_text='Whether supplier has confirmed this order', verbose_name='Supplier Confirmed'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='supplier_confirmed_date',
            field=models.DateField(blank=True, help_text='When supplier confirmed the order', null=True, verbose_name='Supplier Confirmed Date'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='urgency_level',
            field=models.CharField(choices=[('low', 'Low Priority'), ('normal', 'Normal Priority'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='normal', help_text='Priority level for request processing', max_length=10, verbose_name='Urgency Level'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='vat_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='VAT Total'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='workflow_status',
            field=models.CharField(choices=[('req_draft', 'Request: Draft'), ('req_submitted', 'Request: Submitted for Approval'), ('req_approved', 'Request: Approved'), ('req_rejected', 'Request: Rejected'), ('req_converted', 'Request: Converted to Order'), ('ord_draft', 'Order: Draft'), ('ord_sent', 'Order: Sent to Supplier'), ('ord_confirmed', 'Order: Confirmed by Supplier'), ('ord_in_delivery', 'Order: In Delivery Process'), ('ord_completed', 'Order: Completed'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='req_draft', help_text='Detailed workflow status based on document type', max_length=20, verbose_name='Workflow Status'),
        ),
        migrations.AddField(
            model_name='purchasedocumentline',
            name='line_type',
            field=models.CharField(choices=[('from_order', 'From Purchase Order'), ('additional', 'Additional Item'), ('replacement', 'Replacement Item')], default='from_order', help_text='How this line was created', max_length=20, verbose_name='Line Type'),
        ),
        migrations.AddField(
            model_name='purchasedocumentline',
            name='ordered_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Original ordered quantity (for delivery lines from orders)', max_digits=10, null=True, verbose_name='Ordered Quantity'),
        ),
        migrations.AddField(
            model_name='purchasedocumentline',
            name='source_order_line',
            field=models.ForeignKey(blank=True, help_text='Reference to the order line this delivery line came from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_lines', to='purchases.purchasedocumentline', verbose_name='Source Order Line'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='code',
            field=models.CharField(help_text='Unique code like REQ, ORD, DEL, INV', max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='stock_effect',
            field=models.IntegerField(choices=[(1, 'Increases stock'), (-1, 'Decreases stock'), (0, 'No effect')], default=0, help_text='How this document type affects inventory levels', verbose_name='Stock Effect'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='type_key',
            field=models.CharField(choices=[('request', 'Purchase Request'), ('order', 'Purchase Order'), ('delivery', 'Delivery Receipt'), ('invoice', 'Invoice'), ('adjustment', 'Stock Adjustment'), ('transfer', 'Internal Transfer')], max_length=20, verbose_name='Type Key'),
        ),
        migrations.AlterField(
            model_name='purchaseauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Document Created'), ('submitted', 'Request Submitted'), ('approved', 'Request Approved'), ('rejected', 'Request Rejected'), ('converted', 'Request Converted to Order'), ('sent', 'Order Sent to Supplier'), ('confirmed', 'Order Confirmed by Supplier'), ('received', 'Document Received'), ('cancelled', 'Document Cancelled'), ('modified', 'Document Modified'), ('status_changed', 'Status Changed'), ('payment_updated', 'Payment Updated')], max_length=20, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='purchasedocument',
            name='auto_create_invoice',
            field=models.BooleanField(default=False, help_text='Automatically create invoice when document is received', verbose_name='Auto Create Invoice'),
        ),
        migrations.AddIndex(
            model_name='purchasedocument',
            index=models.Index(fields=['document_type', 'workflow_status'], name='purchases_p_documen_862bae_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedocument',
            index=models.Index(fields=['source_document', 'document_type'], name='purchases_p_source__5a529a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedocument',
            index=models.Index(fields=['supplier', 'workflow_status', 'document_type'], name='purchases_p_supplie_c7cf26_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedocument',
            index=models.Index(fields=['delivery_date', 'status'], name='purchases_p_deliver_c49900_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedocumentline',
            index=models.Index(fields=['source_order_line', 'line_type'], name='purchases_p_source__9eda93_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedocumentline',
            index=models.Index(fields=['document', 'line_type'], name='purchases_p_documen_a9470f_idx'),
        ),
    ]
