# Generated by Django 5.2.3 on 2025-07-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_deliveryline_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequestline',
            options={'ordering': ['line_number'], 'verbose_name': 'Purchase Request Line', 'verbose_name_plural': 'Purchase Request Lines'},
        ),
        migrations.RemoveIndex(
            model_name='purchaserequestline',
            name='purchases_p_documen_f53882_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequestline',
            name='purchases_p_product_918f59_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequestline',
            name='purchases_p_suggest_45b34c_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequestline',
            name='purchases_p_priorit_4307dd_idx',
        ),
        migrations.AlterUniqueTogether(
            name='purchaserequestline',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='alternative_products',
            field=models.TextField(blank=True, help_text='Acceptable alternative products if this one is not available', verbose_name='Alternative Products'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='usage_description',
            field=models.TextField(blank=True, help_text='How will this specific item be used?', verbose_name='Usage Description'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(help_text='Current document status - validated by document type', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Estimated price per unit (optional, for planning)', max_digits=12, null=True, verbose_name='Estimated Unit Price'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='quality_notes',
            field=models.TextField(blank=True, help_text='Quality control notes', verbose_name='Quality Notes'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='requested_quantity',
            field=models.DecimalField(decimal_places=3, help_text='How many units are requested', max_digits=12, verbose_name='Requested Quantity'),
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='document',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='item_justification',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='suggested_supplier',
        ),
    ]
