# Generated by Django 5.2.3 on 2025-07-17 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_alter_purchaserequest_business_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestline',
            name='document',
            field=models.ForeignKey(default=1, help_text='Parent purchase request', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchaserequest', verbose_name='Purchase Request'),
            preserve_default=False,
        ),
    ]
