# Generated by Django 5.2.3 on 2025-07-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_purchaserequestline_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryline',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='quantity',
        ),
    ]
