# Generated by Django 5.2.3 on 2025-07-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_remove_deliveryline_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='status',
            field=models.CharField(help_text='Current document status - validated by document type', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(help_text='Current document status - validated by document type', max_length=30, verbose_name='Status'),
        ),
    ]
