# Generated by Django 5.2.3 on 2025-07-20 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_alter_deliveryreceipt_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='document_type',
            field=models.ForeignKey(blank=True, help_text='Auto-detected from model name, or manually override', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.documenttype', verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='document_type',
            field=models.ForeignKey(blank=True, help_text='Auto-detected from model name, or manually override', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.documenttype', verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='document_type',
            field=models.ForeignKey(blank=True, help_text='Auto-detected from model name, or manually override', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.documenttype', verbose_name='Document Type'),
        ),
    ]
