# Generated by Django 5.2.3 on 2025-07-22 07:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_alter_deliveryreceipt_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total discount amount', max_digits=12, verbose_name='Total Discount'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final total including VAT', max_digits=12, verbose_name='Grand Total'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all line totals before VAT', max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='vat_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total VAT amount', max_digits=12, verbose_name='VAT Total'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated discount amount', max_digits=10, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage', max_digits=5, verbose_name='Discount %'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total including VAT', max_digits=12, verbose_name='Line Total'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Price per unit excluding VAT', max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated VAT amount', max_digits=10, verbose_name='VAT Amount'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='VAT rate percentage', max_digits=5, verbose_name='VAT Rate %'),
        ),
    ]
