# Generated by Django 5.2.3 on 2025-07-22 10:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_purchaserequest_discount_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryreceipt',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='grand_total',
        ),
        migrations.AddField(
            model_name='deliveryreceipt',
            name='prices_entered_with_vat',
            field=models.BooleanField(blank=True, help_text='Override location setting. null = use location default, True/False = override for this document', null=True, verbose_name='Prices Entered With VAT'),
        ),
        migrations.AddField(
            model_name='deliveryreceipt',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final total including VAT', max_digits=12, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='prices_entered_with_vat',
            field=models.BooleanField(blank=True, help_text='Override location setting. null = use location default, True/False = override for this document', null=True, verbose_name='Prices Entered With VAT'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final total including VAT', max_digits=12, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='prices_entered_with_vat',
            field=models.BooleanField(blank=True, help_text='Override location setting. null = use location default, True/False = override for this document', null=True, verbose_name='Prices Entered With VAT'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final total including VAT', max_digits=12, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all net amounts (excluding VAT)', max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all net amounts (excluding VAT)', max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all net amounts (excluding VAT)', max_digits=12, verbose_name='Subtotal'),
        ),
    ]
