# Generated by Django 5.2.3 on 2025-07-22 10:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_remove_deliveryreceipt_grand_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryline',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='line_total',
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='entered_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Price as entered by user (before VAT processing)', max_digits=10, verbose_name='Entered Price'),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line amount including VAT', max_digits=12, verbose_name='Gross Amount'),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line amount excluding VAT (after discount)', max_digits=12, verbose_name='Net Amount'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='entered_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Price as entered by user (before VAT processing)', max_digits=10, verbose_name='Entered Price'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line amount including VAT', max_digits=12, verbose_name='Gross Amount'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line amount excluding VAT (after discount)', max_digits=12, verbose_name='Net Amount'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='entered_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Price as entered by user (before VAT processing)', max_digits=10, verbose_name='Entered Price'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line amount including VAT', max_digits=12, verbose_name='Gross Amount'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line amount excluding VAT (after discount)', max_digits=12, verbose_name='Net Amount'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Price per unit ALWAYS excluding VAT', max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT rate percentage from product tax group', max_digits=5, verbose_name='VAT Rate %'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Price per unit ALWAYS excluding VAT', max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT rate percentage from product tax group', max_digits=5, verbose_name='VAT Rate %'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Price per unit ALWAYS excluding VAT', max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT rate percentage from product tax group', max_digits=5, verbose_name='VAT Rate %'),
        ),
    ]
