# Generated by Django 5.2.3 on 2025-08-11 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0015_remove_documenttype_auto_approve_conditions_and_more'),
        ('products', '0002_remove_product_current_avg_cost_and_more'),
        ('purchases', '0015_purchaserequestline_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryline',
            name='serial_numbers',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='quality_approved',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='quality_notes',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='serial_numbers',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='quality_approved',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='quality_notes',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='serial_numbers',
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes specific to this line', verbose_name='Line Notes'),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Quantity for this line', max_digits=10, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes specific to this line', verbose_name='Line Notes'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Quantity for this line', max_digits=10, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes specific to this line', verbose_name='Line Notes'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Quantity for this line', max_digits=10, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='line_number',
            field=models.PositiveIntegerField(help_text='Line number within document (auto-generated)', verbose_name='Line Number'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='product',
            field=models.ForeignKey(help_text='Product for this line', on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='unit',
            field=models.ForeignKey(help_text='Unit of measure', on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.unitofmeasure', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this document was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='created_by',
            field=models.ForeignKey(default=1, help_text='User who created this document', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='document_number',
            field=models.CharField(blank=True, help_text='Auto-generated from document type configuration', max_length=50, unique=True, verbose_name='Document Number'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='document_type',
            field=models.ForeignKey(blank=True, help_text='Auto-detected from model name, or manually set', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.documenttype', verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='external_reference',
            field=models.CharField(blank=True, help_text='External PO number, contract reference, etc.', max_length=100, verbose_name='External Reference'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='status',
            field=models.CharField(blank=True, help_text='Current document status - managed by DocumentService', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this document was last updated', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this document', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this document was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(default=1, help_text='User who created this document', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='document_number',
            field=models.CharField(blank=True, help_text='Auto-generated from document type configuration', max_length=50, unique=True, verbose_name='Document Number'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='document_type',
            field=models.ForeignKey(blank=True, help_text='Auto-detected from model name, or manually set', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.documenttype', verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, help_text='When we expect to receive the goods', null=True, verbose_name='Expected Delivery Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='external_reference',
            field=models.CharField(blank=True, help_text='External PO number, contract reference, etc.', max_length=100, verbose_name='External Reference'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(blank=True, help_text='Current document status - managed by DocumentService', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this document was last updated', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this document', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='line_number',
            field=models.PositiveIntegerField(help_text='Line number within document (auto-generated)', verbose_name='Line Number'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='product',
            field=models.ForeignKey(help_text='Product for this line', on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit',
            field=models.ForeignKey(help_text='Unit of measure', on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.unitofmeasure', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this document was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='created_by',
            field=models.ForeignKey(default=1, help_text='User who created this document', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='document_number',
            field=models.CharField(blank=True, help_text='Auto-generated from document type configuration', max_length=50, unique=True, verbose_name='Document Number'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='document_type',
            field=models.ForeignKey(blank=True, help_text='Auto-detected from model name, or manually set', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.documenttype', verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='external_reference',
            field=models.CharField(blank=True, help_text='External PO number, contract reference, etc.', max_length=100, verbose_name='External Reference'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(blank=True, help_text='Current document status - managed by DocumentService', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this document was last updated', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this document', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='line_number',
            field=models.PositiveIntegerField(help_text='Line number within document (auto-generated)', verbose_name='Line Number'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='product',
            field=models.ForeignKey(help_text='Product for this line', on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='unit',
            field=models.ForeignKey(help_text='Unit of measure', on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.unitofmeasure', verbose_name='Unit'),
        ),
    ]
