# Generated by Django 5.2.3 on 2025-08-12 14:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0017_remove_approvalrule_auto_approve_conditions'),
        ('purchases', '0017_alter_purchaserequestline_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequestline',
            options={'ordering': ['document', 'line_number'], 'verbose_name': 'Purchase Request Line', 'verbose_name_plural': 'Purchase Request Lines'},
        ),
        migrations.RemoveIndex(
            model_name='deliveryline',
            name='purchases_d_quality_327512_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliveryline',
            name='purchases_d_varianc_3b78db_idx',
        ),
        migrations.RemoveField(
            model_name='deliveryline',
            name='requires_special_handling',
        ),
        migrations.AlterUniqueTogether(
            name='purchaserequestline',
            unique_together={('document', 'line_number')},
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='requires_special_storage',
            field=models.BooleanField(default=False, help_text='Needs special storage conditions', verbose_name='Requires Special Storage'),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='storage_location',
            field=models.CharField(blank=True, help_text='Where item was stored (rack/bin/zone)', max_length=50, verbose_name='Storage Location'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='converted_to_order_line',
            field=models.ForeignKey(blank=True, help_text='Order line created from this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request_line_ref', to='purchases.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='item_justification',
            field=models.TextField(blank=True, help_text='Why is this specific item needed?', verbose_name='Item Justification'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='batch_number',
            field=models.CharField(blank=True, db_index=True, help_text='Batch or lot number from supplier', max_length=50, verbose_name='Batch/Lot Number'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, help_text='Product expiry date', null=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='line_number',
            field=models.PositiveIntegerField(default=0, help_text='Line number within document (auto-generated)', verbose_name='Line Number'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='production_date',
            field=models.DateField(blank=True, help_text='When product was manufactured', null=True, verbose_name='Production Date'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='quality_issue_type',
            field=models.CharField(blank=True, choices=[('damaged', 'Damaged'), ('expired', 'Expired'), ('wrong_product', 'Wrong Product'), ('poor_quality', 'Poor Quality'), ('contaminated', 'Contaminated'), ('packaging', 'Packaging Issue'), ('temperature', 'Temperature Issue'), ('other', 'Other')], help_text='Type of quality issue (if any)', max_length=20, verbose_name='Quality Issue Type'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='quality_notes',
            field=models.TextField(blank=True, help_text='Quality control notes', verbose_name='Quality Notes'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='source_order_line',
            field=models.ForeignKey(blank=True, help_text='Order line this delivery fulfills', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_lines', to='purchases.purchaseorderline', verbose_name='Source Order Line'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='temperature_at_receipt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Temperature when received (for cold chain)', max_digits=5, null=True, verbose_name='Temperature (°C)'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Set by DocumentService on creation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='document_number',
            field=models.CharField(blank=True, help_text='Generated by DocumentService', max_length=50, unique=True, verbose_name='Document Number'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='document_type',
            field=models.ForeignKey(blank=True, help_text='Set by DocumentService on creation', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.documenttype', verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='status',
            field=models.CharField(blank=True, help_text='Managed by DocumentService', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Set automatically on update', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Set by DocumentService on creation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='document_number',
            field=models.CharField(blank=True, help_text='Generated by DocumentService', max_length=50, unique=True, verbose_name='Document Number'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='document_type',
            field=models.ForeignKey(blank=True, help_text='Set by DocumentService on creation', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.documenttype', verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(blank=True, help_text='Managed by DocumentService', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Set automatically on update', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='delivered_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text='Total delivered (auto-calculated from delivery receipts)', max_digits=10, verbose_name='Delivered Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending Delivery'), ('partial', 'Partially Delivered'), ('completed', 'Fully Delivered'), ('over_delivered', 'Over Delivered'), ('cancelled', 'Cancelled')], default='pending', editable=False, help_text='Auto-calculated delivery status', max_length=20, verbose_name='Delivery Status'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='line_number',
            field=models.PositiveIntegerField(default=0, help_text='Line number within document (auto-generated)', verbose_name='Line Number'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='source_request_line',
            field=models.ForeignKey(blank=True, help_text='Request line this was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='purchases.purchaserequestline'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Set by DocumentService on creation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='document_number',
            field=models.CharField(blank=True, help_text='Generated by DocumentService', max_length=50, unique=True, verbose_name='Document Number'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='document_type',
            field=models.ForeignKey(blank=True, help_text='Set by DocumentService on creation', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.documenttype', verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(blank=True, help_text='Managed by DocumentService', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Set automatically on update', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchaserequest', verbose_name='Purchase Request'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='line_number',
            field=models.PositiveIntegerField(default=0, help_text='Line number within document (auto-generated)', verbose_name='Line Number'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='priority',
            field=models.IntegerField(default=0, help_text='Priority within request (0=normal, higher=more urgent)', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='requested_quantity',
            field=models.DecimalField(decimal_places=3, help_text='Quantity requested for purchase', max_digits=10, verbose_name='Requested Quantity'),
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='alternative_products',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='usage_description',
        ),
    ]
