# Generated by Django 5.2.3 on 2025-08-12 16:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0018_alter_purchaserequestline_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryline',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deliveryline',
            name='gross_amount',
        ),
        migrations.RemoveField(
            model_name='deliveryline',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='deliveryline',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='gross_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='gross_amount',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='line_subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line total WITHOUT VAT', max_digits=12, verbose_name='Line Subtotal'),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line total INCLUDING VAT', max_digits=12, verbose_name='Line Total'),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Quantity for this line', max_digits=10, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='unit_price_with_vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit price INCLUDING VAT (calculated)', max_digits=10, verbose_name='Unit Price with VAT'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='line_subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line total WITHOUT VAT', max_digits=12, verbose_name='Line Subtotal'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line total INCLUDING VAT', max_digits=12, verbose_name='Line Total'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Quantity for this line', max_digits=10, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='unit_price_with_vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit price INCLUDING VAT (calculated)', max_digits=10, verbose_name='Unit Price with VAT'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='line_subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line total WITHOUT VAT', max_digits=12, verbose_name='Line Subtotal'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line total INCLUDING VAT', max_digits=12, verbose_name='Line Total'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Quantity for this line', max_digits=10, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='unit_price_with_vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit price INCLUDING VAT (calculated)', max_digits=10, verbose_name='Unit Price with VAT'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount', max_digits=10, verbose_name='Discount Amount'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='entered_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price as entered by user (may include VAT)', max_digits=10, null=True, verbose_name='Entered Price'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='line_number',
            field=models.PositiveIntegerField(help_text='Line number within document (auto-generated)', verbose_name='Line Number'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit price WITHOUT VAT (stored value)', max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT amount for this line', max_digits=10, verbose_name='VAT Amount'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='vat_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.200'), help_text='VAT rate (0.20 = 20%)', max_digits=5, verbose_name='VAT Rate'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total discount amount', max_digits=12, verbose_name='Discount Total'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='prices_entered_with_vat',
            field=models.BooleanField(blank=True, help_text='Override location settings. NULL means use location defaults', null=True, verbose_name='Prices Include VAT'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total before VAT and discounts', max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total discount amount', max_digits=12, verbose_name='Discount Total'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='prices_entered_with_vat',
            field=models.BooleanField(blank=True, help_text='Override location settings. NULL means use location defaults', null=True, verbose_name='Prices Include VAT'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total before VAT and discounts', max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount', max_digits=10, verbose_name='Discount Amount'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='entered_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price as entered by user (may include VAT)', max_digits=10, null=True, verbose_name='Entered Price'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='line_number',
            field=models.PositiveIntegerField(help_text='Line number within document (auto-generated)', verbose_name='Line Number'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit price WITHOUT VAT (stored value)', max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT amount for this line', max_digits=10, verbose_name='VAT Amount'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='vat_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.200'), help_text='VAT rate (0.20 = 20%)', max_digits=5, verbose_name='VAT Rate'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total discount amount', max_digits=12, verbose_name='Discount Total'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='prices_entered_with_vat',
            field=models.BooleanField(blank=True, help_text='Override location settings. NULL means use location defaults', null=True, verbose_name='Prices Include VAT'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total before VAT and discounts', max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount', max_digits=10, verbose_name='Discount Amount'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='entered_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price as entered by user (may include VAT)', max_digits=10, null=True, verbose_name='Entered Price'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='line_number',
            field=models.PositiveIntegerField(help_text='Line number within document (auto-generated)', verbose_name='Line Number'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit price WITHOUT VAT (stored value)', max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT amount for this line', max_digits=10, verbose_name='VAT Amount'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='vat_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.200'), help_text='VAT rate (0.20 = 20%)', max_digits=5, verbose_name='VAT Rate'),
        ),
    ]
