# Generated by Django 5.2.3 on 2025-08-12 21:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0019_remove_deliveryline_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryline',
            name='line_subtotal',
        ),
        migrations.RemoveField(
            model_name='deliveryline',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='line_subtotal',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='line_subtotal',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='line_total',
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line amount including VAT', max_digits=12, verbose_name='Gross Amount'),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line amount excluding VAT', max_digits=12, verbose_name='Net Amount'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line amount including VAT', max_digits=12, verbose_name='Gross Amount'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line amount excluding VAT', max_digits=12, verbose_name='Net Amount'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line amount including VAT', max_digits=12, verbose_name='Gross Amount'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line amount excluding VAT', max_digits=12, verbose_name='Net Amount'),
        ),
    ]
