# Generated by Django 5.2.3 on 2025-08-12 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0020_remove_deliveryline_line_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='estimated_price',
        ),
    ]
