# Generated by Django 5.2.3 on 2025-08-15 14:05

from decimal import Decimal
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0021_remove_purchaserequestline_estimated_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='delivery_terms',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='order_method',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='requested_delivery_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='sent_to_supplier_at',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='special_conditions',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier_confirmed_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier_contact_email',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier_contact_person',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier_contact_phone',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='expected_delivery_date',
            field=models.DateField(default=timezone.now, help_text='When we expect this order to be delivered', verbose_name='Expected Delivery Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Mark as urgent for priority processing', verbose_name='Urgent Order'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier_confirmed',
            field=models.BooleanField(default=False, help_text='Has supplier confirmed this order?', verbose_name='Supplier Confirmed'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier_order_reference',
            field=models.CharField(blank=True, help_text='Reference number from supplier system', max_length=100, verbose_name='Supplier Order Reference'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='delivered_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Total quantity delivered (auto-calculated)', max_digits=10, verbose_name='Delivered Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Delivered'), ('completed', 'Fully Delivered')], default='pending', help_text='Delivery status of this line', max_length=20, verbose_name='Delivery Status'),
        ),
    ]
