# Generated by Django 5.2.3 on 2025-08-20 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_customer_price_group'),
        ('purchases', '0022_remove_purchaseorder_delivery_terms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='The supplier for this document', null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='The supplier for this document', null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='The supplier for this document', null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
            preserve_default=False,
        ),
    ]
