# Generated by Django 5.2.3 on 2025-08-20 17:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nomenclatures', '0023_convert_to_generic_fk'),
        ('partners', '0003_customer_code_supplier_code'),
        ('products', '0002_remove_product_current_avg_cost_and_more'),
        ('purchases', '0023_alter_deliveryreceipt_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryline',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='notes',
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='description',
            field=models.TextField(blank=True, help_text='Additional description for this line', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='deliveryreceipt',
            name='partner_content_type',
            field=models.ForeignKey(blank=True, help_text='Type of partner (Supplier, Customer, etc.)', limit_choices_to=models.Q(models.Q(('app_label', 'partners'), ('model__in', ['supplier', 'customer'])), models.Q(('app_label', 'hr'), ('model', 'employee')), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Partner Type'),
        ),
        migrations.AddField(
            model_name='deliveryreceipt',
            name='partner_object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the partner object', null=True, verbose_name='Partner ID'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='partner_content_type',
            field=models.ForeignKey(blank=True, help_text='Type of partner (Supplier, Customer, etc.)', limit_choices_to=models.Q(models.Q(('app_label', 'partners'), ('model__in', ['supplier', 'customer'])), models.Q(('app_label', 'hr'), ('model', 'employee')), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Partner Type'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='partner_object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the partner object', null=True, verbose_name='Partner ID'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='description',
            field=models.TextField(blank=True, help_text='Additional description for this line', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='partner_content_type',
            field=models.ForeignKey(blank=True, help_text='Type of partner (Supplier, Customer, etc.)', limit_choices_to=models.Q(models.Q(('app_label', 'partners'), ('model__in', ['supplier', 'customer'])), models.Q(('app_label', 'hr'), ('model', 'employee')), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Partner Type'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='partner_object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the partner object', null=True, verbose_name='Partner ID'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='description',
            field=models.TextField(blank=True, help_text='Additional description for this line', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='line_number',
            field=models.PositiveSmallIntegerField(help_text='Sequential line number within document', verbose_name='Line Number'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Quantity in specified unit', max_digits=12, verbose_name='Quantity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.unitofmeasure', verbose_name='Unit of Measure'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use partner field instead', null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.supplier', verbose_name='Supplier (Legacy)'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use partner field instead', null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.supplier', verbose_name='Supplier (Legacy)'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='line_number',
            field=models.PositiveSmallIntegerField(help_text='Sequential line number within document', verbose_name='Line Number'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Quantity in specified unit', max_digits=12, verbose_name='Quantity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.unitofmeasure', verbose_name='Unit of Measure'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use partner field instead', null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.supplier', verbose_name='Supplier (Legacy)'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='line_number',
            field=models.PositiveSmallIntegerField(help_text='Sequential line number within document', verbose_name='Line Number'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Quantity in specified unit', max_digits=12, verbose_name='Quantity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.unitofmeasure', verbose_name='Unit of Measure'),
        ),
    ]
