# Generated by Django 5.2.3 on 2025-08-20 19:51

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0008_inventorylocation_purchase_prices_include_vat_and_more'),
        ('nomenclatures', '0023_convert_to_generic_fk'),
        ('partners', '0003_customer_code_supplier_code'),
        ('products', '0002_remove_product_current_avg_cost_and_more'),
        ('purchases', '0024_remove_deliveryline_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryreceipt',
            options={'ordering': ['-delivery_date', '-received_at'], 'permissions': [('can_receive_delivery', 'Can receive deliveries'), ('can_perform_quality_control', 'Can perform quality control'), ('can_process_to_inventory', 'Can process deliveries to inventory'), ('can_view_quality_details', 'Can view quality control details')], 'verbose_name': 'Delivery Receipt', 'verbose_name_plural': 'Delivery Receipts'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at'], 'permissions': [('can_send_to_supplier', 'Can send orders to supplier'), ('can_confirm_from_supplier', 'Can confirm orders from supplier'), ('can_create_delivery', 'Can create deliveries from orders'), ('can_view_supplier_details', 'Can view supplier details')], 'verbose_name': 'Purchase Order', 'verbose_name_plural': 'Purchase Orders'},
        ),
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'ordering': ['-created_at'], 'permissions': [('can_approve_purchase_request', 'Can approve purchase requests'), ('can_convert_to_order', 'Can convert requests to orders'), ('can_view_financial_summary', 'Can view financial summary')], 'verbose_name': 'Purchase Request', 'verbose_name_plural': 'Purchase Requests'},
        ),
        migrations.RemoveIndex(
            model_name='deliveryline',
            name='purchases_d_quality_477e72_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliveryreceipt',
            name='purchases_d_supplie_a39903_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliveryreceipt',
            name='purchases_d_creatio_d6b17d_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliveryreceipt',
            name='purchases_d_has_qua_00ed64_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliveryreceipt',
            name='purchases_d_has_var_d14a16_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliveryreceipt',
            name='purchases_d_receive_d116c8_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='purchases_p_status_81c61e_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='purchases_p_supplie_03ca62_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='purchases_p_is_urge_7c5c52_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='purchases_p_deliver_d0bdbd_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequest',
            name='purchases_p_status_4ce46a_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequest',
            name='purchases_p_request_869bd1_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequest',
            name='purchases_p_approve_30a0f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequest',
            name='purchases_p_request_cb6533_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequestline',
            name='purchases_p_suggest_45b34c_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequestline',
            name='purchases_p_priorit_4307dd_idx',
        ),
        migrations.RemoveField(
            model_name='deliveryline',
            name='description',
        ),
        migrations.RemoveField(
            model_name='deliveryline',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='deliveryline',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='deliveryline',
            name='entered_price',
        ),
        migrations.RemoveField(
            model_name='deliveryline',
            name='expected_quantity',
        ),
        migrations.RemoveField(
            model_name='deliveryline',
            name='gross_amount',
        ),
        migrations.RemoveField(
            model_name='deliveryline',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='deliveryline',
            name='production_date',
        ),
        migrations.RemoveField(
            model_name='deliveryline',
            name='received_quantity',
        ),
        migrations.RemoveField(
            model_name='deliveryline',
            name='requires_special_storage',
        ),
        migrations.RemoveField(
            model_name='deliveryline',
            name='storage_location',
        ),
        migrations.RemoveField(
            model_name='deliveryline',
            name='temperature_at_receipt',
        ),
        migrations.RemoveField(
            model_name='deliveryline',
            name='unit_price_with_vat',
        ),
        migrations.RemoveField(
            model_name='deliveryline',
            name='variance_quantity',
        ),
        migrations.RemoveField(
            model_name='deliveryline',
            name='vat_amount',
        ),
        migrations.RemoveField(
            model_name='deliveryline',
            name='vat_rate',
        ),
        migrations.RemoveField(
            model_name='deliveryreceipt',
            name='creation_type',
        ),
        migrations.RemoveField(
            model_name='deliveryreceipt',
            name='delivery_instructions',
        ),
        migrations.RemoveField(
            model_name='deliveryreceipt',
            name='delivery_note_number',
        ),
        migrations.RemoveField(
            model_name='deliveryreceipt',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='deliveryreceipt',
            name='driver_phone',
        ),
        migrations.RemoveField(
            model_name='deliveryreceipt',
            name='has_quality_issues',
        ),
        migrations.RemoveField(
            model_name='deliveryreceipt',
            name='has_variances',
        ),
        migrations.RemoveField(
            model_name='deliveryreceipt',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='deliveryreceipt',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='deliveryreceipt',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='deliveryreceipt',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='deliveryreceipt',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='deliveryreceipt',
            name='quality_approved',
        ),
        migrations.RemoveField(
            model_name='deliveryreceipt',
            name='quality_checked',
        ),
        migrations.RemoveField(
            model_name='deliveryreceipt',
            name='quality_inspector',
        ),
        migrations.RemoveField(
            model_name='deliveryreceipt',
            name='source_orders',
        ),
        migrations.RemoveField(
            model_name='deliveryreceipt',
            name='special_handling_notes',
        ),
        migrations.RemoveField(
            model_name='deliveryreceipt',
            name='variance_notes',
        ),
        migrations.RemoveField(
            model_name='deliveryreceipt',
            name='vehicle_info',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='confirmed_quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='description',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='entered_price',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='gross_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='unit_price_with_vat',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='vat_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='vat_rate',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='approval_required',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='business_justification',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='expected_usage',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='request_type',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='urgency_level',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='converted_to_order_line',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='description',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='entered_price',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='gross_amount',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='item_justification',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='suggested_supplier',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='unit_price_with_vat',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='vat_amount',
        ),
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='vat_rate',
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes for this line', verbose_name='Line Notes'),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='quality_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Quality Checked At'),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='quality_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_checked_delivery_lines', to=settings.AUTH_USER_MODEL, verbose_name='Quality Checked By'),
        ),
        migrations.AddField(
            model_name='deliveryreceipt',
            name='delivery_driver_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Delivery Driver Name'),
        ),
        migrations.AddField(
            model_name='deliveryreceipt',
            name='delivery_vehicle_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Vehicle Number'),
        ),
        migrations.AddField(
            model_name='deliveryreceipt',
            name='quality_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Quality Checked At'),
        ),
        migrations.AddField(
            model_name='deliveryreceipt',
            name='quality_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_checked_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Quality Checked By'),
        ),
        migrations.AddField(
            model_name='deliveryreceipt',
            name='quality_status',
            field=models.CharField(choices=[('pending', 'Pending Quality Control'), ('approved', 'Quality Approved'), ('rejected', 'Quality Rejected'), ('partial', 'Partially Approved')], default='pending', help_text='Overall quality control status', max_length=20, verbose_name='Quality Status'),
        ),
        migrations.AddField(
            model_name='deliveryreceipt',
            name='source_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='purchases.purchaseorder', verbose_name='Source Order'),
        ),
        migrations.AddField(
            model_name='deliveryreceipt',
            name='supplier_delivery_reference',
            field=models.CharField(blank=True, help_text='Supplier reference for this delivery', max_length=100, verbose_name='Supplier Delivery Reference'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sent_to_supplier_at',
            field=models.DateTimeField(blank=True, help_text='When order was sent to supplier', null=True, verbose_name='Sent to Supplier At'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_confirmed_date',
            field=models.DateField(blank=True, help_text='When supplier confirmed the order', null=True, verbose_name='Supplier Confirmed Date'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes for this line', verbose_name='Line Notes'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', help_text='Request priority level', max_length=20, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='required_by_date',
            field=models.DateField(blank=True, help_text='When the items are needed', null=True, verbose_name='Required By Date'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Estimated unit price for budgeting', max_digits=15, null=True, verbose_name='Estimated Price'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes for this line', verbose_name='Line Notes'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Batch/lot number for traceability', max_length=50, verbose_name='Batch Number'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.deliveryreceipt', verbose_name='Delivery'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Product expiry date for this batch', null=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='line_number',
            field=models.PositiveIntegerField(help_text='Sequential line number within document', verbose_name='Line Number'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='quality_approved',
            field=models.BooleanField(help_text='True=approved, False=rejected, None=pending', null=True, verbose_name='Quality Approved'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='quality_issue_type',
            field=models.CharField(blank=True, choices=[('', 'No Issues'), ('damaged', 'Damaged'), ('expired', 'Expired'), ('wrong_product', 'Wrong Product'), ('wrong_quantity', 'Wrong Quantity'), ('poor_quality', 'Poor Quality'), ('packaging_issues', 'Packaging Issues'), ('other', 'Other Issues')], help_text='Type of quality issue if rejected', max_length=20, verbose_name='Quality Issue Type'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='quality_notes',
            field=models.TextField(blank=True, help_text='Detailed notes about quality issues', verbose_name='Quality Notes'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Actual delivered quantity', max_digits=15, verbose_name='Delivered Quantity'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='source_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_lines', to='purchases.purchaseorderline', verbose_name='Source Order Line'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='unit',
            field=models.CharField(help_text='Unit of measure for this line', max_length=20, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, help_text='Price per unit from order', max_digits=15, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when goods were delivered', verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='quality_notes',
            field=models.TextField(blank=True, help_text='Notes about quality control process', verbose_name='Quality Notes'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now, help_text='Timestamp when delivery was recorded', verbose_name='Received At'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='received_by',
            field=models.ForeignKey(default=1, help_text='User who received the delivery', on_delete=django.db.models.deletion.PROTECT, related_name='received_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Received By'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='source_request',
            field=models.ForeignKey(blank=True, help_text='Request this order was created from (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_orders', to='purchases.purchaserequest', verbose_name='Source Request'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='delivered_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Total quantity delivered (aggregated from delivery lines)', max_digits=15, verbose_name='Delivered Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchaseorder', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='line_number',
            field=models.PositiveIntegerField(help_text='Sequential line number within document', verbose_name='Line Number'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='ordered_quantity',
            field=models.DecimalField(decimal_places=3, help_text='Final ordered quantity', max_digits=15, verbose_name='Ordered Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Quantity in specified unit', max_digits=15, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='source_request_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='converted_to_order_line', to='purchases.purchaserequestline', verbose_name='Source Request Line'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit',
            field=models.CharField(help_text='Unit of measure for this line', max_length=20, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, help_text='Price per unit', max_digits=15, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='converted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='converted_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Converted By'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='converted_to_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_request', to='purchases.purchaseorder', verbose_name='Converted to Order'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if applicable', verbose_name='Rejection Reason'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchaserequest', verbose_name='Request'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='line_number',
            field=models.PositiveIntegerField(help_text='Sequential line number within document', verbose_name='Line Number'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='requested_quantity',
            field=models.DecimalField(decimal_places=3, help_text='Quantity requested in specified unit', max_digits=15, verbose_name='Requested Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='unit',
            field=models.CharField(help_text='Unit of measure for this line', max_length=20, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='deliveryline',
            index=models.Index(fields=['quality_approved', 'quality_checked_at'], name='purchases_d_quality_045615_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryreceipt',
            index=models.Index(fields=['delivery_date', 'supplier'], name='purchases_d_deliver_2bdd75_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryreceipt',
            index=models.Index(fields=['quality_status', 'quality_checked_at'], name='purchases_d_quality_a2f219_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryreceipt',
            index=models.Index(fields=['source_order'], name='purchases_d_source__b8f366_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryreceipt',
            index=models.Index(fields=['received_by', 'received_at'], name='purchases_d_receive_f4fd1e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status', 'created_at'], name='purchases_p_status_5df029_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'status'], name='purchases_p_supplie_1eb951_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier_confirmed', 'supplier_confirmed_date'], name='purchases_p_supplie_fb7353_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['expected_delivery_date'], name='purchases_p_expecte_17bb41_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['delivery_status'], name='purchases_p_deliver_3b3c22_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status', 'created_at'], name='purchases_p_status_e74967_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['supplier', 'status'], name='purchases_p_supplie_b884ac_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['approved_by', 'approved_at'], name='purchases_p_approve_41e38c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['required_by_date'], name='purchases_p_require_718aa0_idx'),
        ),
    ]
