# Generated by Django 5.2.3 on 2025-08-20 22:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0025_alter_deliveryreceipt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryline',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total discount amount', max_digits=12, verbose_name='Discount Total'),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='prices_entered_with_vat',
            field=models.BooleanField(blank=True, help_text='Override location settings. NULL means use location defaults', null=True, verbose_name='Prices Include VAT'),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total before VAT and discounts', max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final total including VAT', max_digits=12, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='vat_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total VAT amount', max_digits=12, verbose_name='VAT Total'),
        ),
        migrations.AddField(
            model_name='deliveryreceipt',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Whether this document has been paid', verbose_name='Is Paid'),
        ),
        migrations.AddField(
            model_name='deliveryreceipt',
            name='payment_date',
            field=models.DateField(blank=True, help_text='When payment was made', null=True, verbose_name='Payment Date'),
        ),
        migrations.AddField(
            model_name='deliveryreceipt',
            name='payment_method',
            field=models.CharField(blank=True, help_text='How payment was made', max_length=50, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total discount amount', max_digits=12, verbose_name='Discount Total'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='prices_entered_with_vat',
            field=models.BooleanField(blank=True, help_text='Override location settings. NULL means use location defaults', null=True, verbose_name='Prices Include VAT'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total before VAT and discounts', max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final total including VAT', max_digits=12, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='vat_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total VAT amount', max_digits=12, verbose_name='VAT Total'),
        ),
    ]
