# Generated by Django 5.2.3 on 2025-08-21 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('purchases', '0026_deliveryline_discount_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryreceipt',
            name='location',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='location',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='location',
        ),
        migrations.AddField(
            model_name='deliveryreceipt',
            name='location_content_type',
            field=models.ForeignKey(blank=True, help_text='Type of location (InventoryLocation, OnlineStore, etc.)', limit_choices_to=models.Q(models.Q(('app_label', 'inventory'), ('model', 'inventorylocation')), models.Q(('app_label', 'sales'), ('model', 'onlinestore')), models.Q(('app_label', 'partners'), ('model', 'customersite')), models.Q(('app_label', 'hr'), ('model', 'office')), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_as_location', to='contenttypes.contenttype', verbose_name='Location Type'),
        ),
        migrations.AddField(
            model_name='deliveryreceipt',
            name='location_object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the location object', null=True, verbose_name='Location ID'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='location_content_type',
            field=models.ForeignKey(blank=True, help_text='Type of location (InventoryLocation, OnlineStore, etc.)', limit_choices_to=models.Q(models.Q(('app_label', 'inventory'), ('model', 'inventorylocation')), models.Q(('app_label', 'sales'), ('model', 'onlinestore')), models.Q(('app_label', 'partners'), ('model', 'customersite')), models.Q(('app_label', 'hr'), ('model', 'office')), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_as_location', to='contenttypes.contenttype', verbose_name='Location Type'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='location_object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the location object', null=True, verbose_name='Location ID'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='location_content_type',
            field=models.ForeignKey(blank=True, help_text='Type of location (InventoryLocation, OnlineStore, etc.)', limit_choices_to=models.Q(models.Q(('app_label', 'inventory'), ('model', 'inventorylocation')), models.Q(('app_label', 'sales'), ('model', 'onlinestore')), models.Q(('app_label', 'partners'), ('model', 'customersite')), models.Q(('app_label', 'hr'), ('model', 'office')), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_as_location', to='contenttypes.contenttype', verbose_name='Location Type'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='location_object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the location object', null=True, verbose_name='Location ID'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='partner_content_type',
            field=models.ForeignKey(blank=True, help_text='Type of partner (Supplier, Customer, etc.)', limit_choices_to=models.Q(models.Q(('app_label', 'partners'), ('model__in', ['supplier', 'customer'])), models.Q(('app_label', 'hr'), ('model', 'employee')), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_as_partner', to='contenttypes.contenttype', verbose_name='Partner Type'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='partner_content_type',
            field=models.ForeignKey(blank=True, help_text='Type of partner (Supplier, Customer, etc.)', limit_choices_to=models.Q(models.Q(('app_label', 'partners'), ('model__in', ['supplier', 'customer'])), models.Q(('app_label', 'hr'), ('model', 'employee')), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_as_partner', to='contenttypes.contenttype', verbose_name='Partner Type'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='partner_content_type',
            field=models.ForeignKey(blank=True, help_text='Type of partner (Supplier, Customer, etc.)', limit_choices_to=models.Q(models.Q(('app_label', 'partners'), ('model__in', ['supplier', 'customer'])), models.Q(('app_label', 'hr'), ('model', 'employee')), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_as_partner', to='contenttypes.contenttype', verbose_name='Partner Type'),
        ),
    ]
