# Generated by Django 5.2.3 on 2025-08-25 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0026_remove_documenttype_nomenclatur_auto_cr_cc5303_idx_and_more'),
        ('purchases', '0028_remove_deliveryreceipt_purchases_d_deliver_2bdd75_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='notes',
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='description',
            field=models.TextField(blank=True, help_text='Additional description for this line', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='line_number',
            field=models.PositiveSmallIntegerField(help_text='Sequential line number within document', verbose_name='Line Number'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.unitofmeasure', verbose_name='Unit of Measure'),
        ),
    ]
