# Generated by Django 5.2.3 on 2025-08-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0029_remove_purchaserequestline_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequestline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
    ]
