# Generated by Django 5.2.3 on 2025-08-25 10:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0026_remove_documenttype_nomenclatur_auto_cr_cc5303_idx_and_more'),
        ('purchases', '0030_alter_purchaserequestline_created_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='purchaseorderline',
            name='purchases_p_deliver_23b15c_idx',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='delivered_quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='discount_total',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='prices_entered_with_vat',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='total',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='vat_total',
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='description',
            field=models.TextField(blank=True, help_text='Additional description for this line', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount', max_digits=10, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage', max_digits=5, verbose_name='Discount %'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='entered_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price as entered by user (may include VAT)', max_digits=10, null=True, verbose_name='Entered Price'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line amount including VAT', max_digits=12, verbose_name='Gross Amount'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line amount excluding VAT', max_digits=12, verbose_name='Net Amount'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='unit_price_with_vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit price INCLUDING VAT (calculated)', max_digits=10, verbose_name='Unit Price with VAT'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT amount for this line', max_digits=10, verbose_name='VAT Amount'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='vat_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.200'), help_text='VAT rate (0.20 = 20%)', max_digits=5, verbose_name='VAT Rate'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchaseorder', verbose_name='Purchase Order'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='line_number',
            field=models.PositiveSmallIntegerField(help_text='Sequential line number within document', verbose_name='Line Number'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='ordered_quantity',
            field=models.DecimalField(decimal_places=3, help_text='Quantity ordered from supplier', max_digits=15, verbose_name='Ordered Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='source_request_line',
            field=models.ForeignKey(blank=True, help_text='Original request line this order line was created from', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='converted_to_order_line', to='purchases.purchaserequestline', verbose_name='Source Request Line'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.unitofmeasure', verbose_name='Unit of Measure'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit price WITHOUT VAT (stored value)', max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
