# Generated by Django 5.2.3 on 2025-07-12 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('purchases', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='purchase_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchasedocument', verbose_name='Purchase Document'),
        ),
    ]
