# Generated by Django 5.2.3 on 2025-07-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylocation',
            name='purchase_prices_include_vat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='sales_prices_include_vat',
            field=models.BooleanField(default=True),
        ),
    ]
