# Generated by Django 5.2.3 on 2025-08-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybatch',
            name='cost_price',
            field=models.DecimalField(decimal_places=4, help_text='Cost price for this batch (4 decimal precision)', max_digits=12, verbose_name='Cost Price'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='avg_cost',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Weighted average cost price (4 decimal precision for calculations)', max_digits=12, verbose_name='Average Cost'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='last_purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Last purchase cost for this location (4 decimal precision)', max_digits=12, null=True, verbose_name='Last Purchase Cost'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='last_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Last sale price for this location (currency precision)', max_digits=12, null=True, verbose_name='Last Sale Price'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='cost_price',
            field=models.DecimalField(decimal_places=4, help_text='Actual unit cost price for this specific movement (4 decimal precision)', max_digits=12, verbose_name='Cost Price'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='profit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated profit per unit (sale_price - cost_price)', max_digits=12, null=True, verbose_name='Profit Amount'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sale price per unit (for OUT movements from sales, currency precision)', max_digits=12, null=True, verbose_name='Sale Price'),
        ),
    ]
