# Generated by Django 5.2.3 on 2025-07-14 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='delivery_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='purchases.deliveryreceipt', verbose_name='Delivery Receipt'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_transfers', to='inventory.inventorylocation', verbose_name='From Location'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventorylocation', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='products.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbound_transfers', to='inventory.inventorylocation', verbose_name='To Location'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['location', 'current_qty'], name='inventory_i_locatio_3548fd_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['product', 'current_qty'], name='inventory_i_product_f921a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('location', 'product')},
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['location', 'product', 'remaining_qty'], name='inventory_i_locatio_58b32a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['expiry_date', 'remaining_qty'], name='inventory_i_expiry__fa02d2_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['batch_number'], name='inventory_i_batch_n_9bceae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorybatch',
            unique_together={('location', 'product', 'batch_number', 'expiry_date')},
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['location', 'product', '-created_at'], name='inventory_i_locatio_7170e0_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['movement_type', '-created_at'], name='inventory_i_movemen_979428_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['batch_number'], name='inventory_i_batch_n_e6df65_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['movement_date'], name='inventory_i_movemen_0f2323_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['source_document_number'], name='inventory_i_source__cf704e_idx'),
        ),
    ]
