# Generated by Django 5.2.3 on 2025-07-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorylocation_purchase_prices_include_vat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='source_document_type',
            field=models.CharField(blank=True, choices=[('PURCHASES', 'Purchase Order'), ('SALE', 'Sale'), ('TRANSFER', 'Transfer Order'), ('ADJUSTMENT', 'Adjustment'), ('PRODUCTION', 'Production Order'), ('CYCLE_COUNT', 'Cycle Count')], max_length=20, verbose_name='Source Document Type'),
        ),
    ]
