# Generated by Django 5.2.3 on 2025-07-14 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('partners', '0002_customer_price_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code like POS01, CASH1', max_length=10, unique=True, verbose_name='POS Code')),
                ('name', models.CharField(max_length=100, verbose_name='POS Location Name')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('fiscal_device_serial', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Fiscal Device Serial')),
                ('fiscal_device_number', models.CharField(blank=True, help_text='Official registration number', max_length=20, verbose_name='Fiscal Device Number')),
                ('allow_negative_stock', models.BooleanField(default=False, help_text='Whether to allow sales when stock is insufficient', verbose_name='Allow Negative Stock Sales')),
                ('require_customer', models.BooleanField(default=False, help_text='Whether customer selection is mandatory', verbose_name='Require Customer')),
                ('receipt_printer', models.CharField(blank=True, help_text='Receipt printer name/address', max_length=100, verbose_name='Receipt Printer')),
                ('opens_at', models.TimeField(blank=True, null=True, verbose_name='Opens At')),
                ('closes_at', models.TimeField(blank=True, null=True, verbose_name='Closes At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('default_customer', models.ForeignKey(blank=True, help_text='Default customer for anonymous sales', null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.customer')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_locations', to='inventory.inventorylocation', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'POS Location',
                'verbose_name_plural': 'POS Locations',
            },
        ),
    ]
