# Generated by Django 5.2.3 on 2025-08-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_inventorylocation_purchase_prices_include_vat_and_more'),
        ('products', '0002_remove_product_current_avg_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['location', 'product'], 'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='conversion_date',
            field=models.DateTimeField(blank=True, help_text='When product was converted to batch tracking', null=True, verbose_name='Conversion Date'),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='original_source',
            field=models.CharField(blank=True, help_text='Source of this batch (for unknown batches)', max_length=100, verbose_name='Original Source'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Last purchase cost for this location', max_digits=10, null=True, verbose_name='Last Purchase Cost'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Purchase Date'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_sale_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Sale Date'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Last sale price for this location', max_digits=10, null=True, verbose_name='Last Sale Price'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='avg_cost',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Weighted average cost price', max_digits=10, verbose_name='Average Cost'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='reserved_qty',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Quantity reserved for orders/transfers', max_digits=12, verbose_name='Reserved Quantity'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['is_unknown_batch'], name='inventory_i_is_unkn_cb1e92_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['current_qty'], name='inventory_i_current_9bef1f_idx'),
        ),
    ]
