# Generated by Django 5.2.3 on 2025-08-09 11:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventoryitem_options_and_more'),
        ('products', '0002_remove_product_current_avg_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventorymovement',
            name='inventory_i_locatio_7170e0_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorymovement',
            name='inventory_i_movemen_979428_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorymovement',
            name='inventory_i_source__cf704e_idx',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='notes',
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='profit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated profit per unit (sale_price - cost_price)', max_digits=10, null=True, verbose_name='Profit Amount'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sale price per unit (for OUT movements from sales)', max_digits=10, null=True, verbose_name='Sale Price'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='source_document_line_id',
            field=models.PositiveIntegerField(blank=True, help_text='Reference to specific line in source document', null=True, verbose_name='Source Document Line ID'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Business date of the movement', verbose_name='Movement Date'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='reason',
            field=models.CharField(blank=True, help_text='Reason for this movement', max_length=200, verbose_name='Reason'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['location', 'product', 'movement_date'], name='inventory_i_locatio_6b42f5_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['movement_type', 'movement_date'], name='inventory_i_movemen_bea0b0_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['source_document_type', 'source_document_number'], name='inventory_i_source__1f0202_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['created_at'], name='inventory_i_created_75a91c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['sale_price', 'movement_date'], name='inventory_i_sale_pr_efd914_idx'),
        ),
    ]
