# Generated by Django 5.2.3 on 2025-08-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventorymovement_inventory_i_locatio_7170e0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='source_document_type',
            field=models.CharField(blank=True, db_index=True, help_text='Automatically set by system services', max_length=30, verbose_name='Source Document Type'),
        ),
    ]
