# Generated by Django 5.2.3 on 2025-08-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventorymovement_source_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylocation',
            name='purchase_prices_include_vat',
            field=models.BooleanField(default=False, help_text='Whether purchase prices for this location include VAT by default. Usually False for B2B purchases.', verbose_name='Purchase Prices Include VAT'),
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='sales_prices_include_vat',
            field=models.BooleanField(default=True, help_text='Whether sales prices for this location include VAT by default. Usually True for B2C sales.', verbose_name='Sales Prices Include VAT'),
        ),
    ]
