# Generated by Django 5.2.3 on 2025-07-12 10:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomenclatures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/logos/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('category', models.CharField(choices=[('FOOD', 'Food Products'), ('NONFOOD', 'Non-Food Products'), ('TOBACCO', 'Tobacco Products'), ('ALCOHOL', 'Alcoholic Beverages'), ('SERVICE', 'Services')], default='FOOD', max_length=20, verbose_name='Category')),
                ('requires_expiry_date', models.BooleanField(default=False, verbose_name='Requires Expiry Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Product Type',
                'verbose_name_plural': 'Product Types',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productgroup')),
            ],
            options={
                'verbose_name': 'Product Group',
                'verbose_name_plural': 'Product Groups',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique internal product code', max_length=50, unique=True, verbose_name='Product Code')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('unit_type', models.CharField(choices=[('PIECE', 'Piece/Count'), ('WEIGHT', 'Weight (kg, g)'), ('VOLUME', 'Volume (l, ml)'), ('LENGTH', 'Length (m, cm)')], default='PIECE', help_text='Defines how this product is measured/sold', max_length=10, verbose_name='Unit Type')),
                ('track_batches', models.BooleanField(default=False, help_text='Enable batch/lot tracking for this product', verbose_name='Track Batches')),
                ('current_avg_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Weighted average purchase cost', max_digits=10, verbose_name='Current Average Cost')),
                ('current_stock_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Total quantity across all locations', max_digits=12, verbose_name='Current Stock Quantity')),
                ('last_purchase_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Cost from most recent purchase', max_digits=10, verbose_name='Last Purchase Cost')),
                ('last_purchase_date', models.DateField(blank=True, null=True, verbose_name='Last Purchase Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('base_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.unitofmeasure', verbose_name='Base Unit')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand', verbose_name='Brand')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatures.producttype', verbose_name='Product Type')),
                ('tax_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.taxgroup', verbose_name='Tax Group')),
                ('product_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productgroup', verbose_name='Product Group')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProductPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_factor', models.DecimalField(decimal_places=4, help_text='How many base units in this packaging', max_digits=10, verbose_name='Conversion Factor')),
                ('is_default_sale_unit', models.BooleanField(default=False, help_text='Default unit for POS sales', verbose_name='Default Sale Unit')),
                ('is_default_purchase_unit', models.BooleanField(default=False, help_text='Default unit for purchases', verbose_name='Default Purchase Unit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagings', to='products.product', verbose_name='Product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.unitofmeasure', verbose_name='Packaging Unit')),
            ],
            options={
                'verbose_name': 'Product Packaging',
                'verbose_name_plural': 'Product Packagings',
                'ordering': ['product', '-is_default_sale_unit', 'unit'],
            },
        ),
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(help_text='EAN13, UPC, or internal barcode', max_length=50, unique=True, verbose_name='Barcode')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary barcode for this product', verbose_name='Is Primary')),
                ('barcode_type', models.CharField(choices=[('STANDARD', 'Standard EAN/UPC'), ('WEIGHT', 'Weight-based (28xxx)'), ('INTERNAL', 'Internal Code')], default='STANDARD', max_length=10, verbose_name='Barcode Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='products.product', verbose_name='Product')),
                ('packaging', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productpackaging', verbose_name='Packaging')),
            ],
            options={
                'verbose_name': 'Product Barcode',
                'verbose_name_plural': 'Product Barcodes',
                'ordering': ['product', '-is_primary', 'barcode'],
            },
        ),
        migrations.CreateModel(
            name='ProductPLU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plu_code', models.CharField(help_text='PLU code for weight-based products', max_length=10, verbose_name='PLU Code')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary PLU code for this product', verbose_name='Is Primary')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority = preferred when conflicts', verbose_name='Priority')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plu_codes', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product PLU Code',
                'verbose_name_plural': 'Product PLU Codes',
                'ordering': ['-priority', '-is_primary', 'plu_code'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='products_pr_code_4c2607_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'product_group'], name='products_pr_is_acti_ce4c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['unit_type', 'is_active'], name='products_pr_unit_ty_e57277_idx'),
        ),
        migrations.AddConstraint(
            model_name='productpackaging',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_sale_unit', True)), fields=('product',), name='unique_default_sale_unit_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productpackaging',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_purchase_unit', True)), fields=('product',), name='unique_default_purchase_unit_per_product'),
        ),
        migrations.AlterUniqueTogether(
            name='productpackaging',
            unique_together={('product', 'unit')},
        ),
        migrations.AddConstraint(
            model_name='productbarcode',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='unique_primary_barcode_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productplu',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='unique_primary_plu_per_product'),
        ),
        migrations.AlterUniqueTogether(
            name='productplu',
            unique_together={('product', 'plu_code')},
        ),
    ]
