# Generated by Django 5.2.3 on 2025-07-14 18:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0002_poslocation_location'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatures.brand', verbose_name='Brand'),
        ),
        migrations.RemoveField(
            model_name='productgroup',
            name='parent',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatures.productgroup', verbose_name='Product Group'),
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
        migrations.AlterModelOptions(
            name='productpackaging',
            options={'ordering': ['product', 'conversion_factor'], 'verbose_name': 'Product Packaging', 'verbose_name_plural': 'Product Packagings'},
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Подробно описание на продукта', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_sale_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Sale Date'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_sale_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Last Sale Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_expiry_date',
            field=models.BooleanField(default=False, help_text='Изисква срок на годност', verbose_name='Requires Expiry Date'),
        ),
        migrations.AddField(
            model_name='product',
            name='track_serial_numbers',
            field=models.BooleanField(default=False, help_text='Проследяване на серийни номера (за скъпи стоки)', verbose_name='Track Serial Numbers'),
        ),
        migrations.AddField(
            model_name='productpackaging',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Тегло на празната опаковка', max_digits=8, null=True, verbose_name='Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_unit',
            field=models.ForeignKey(help_text='Основна мерна единица за съхранение', on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.unitofmeasure', verbose_name='Base Unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(help_text='Уникален вътрешен код', max_length=50, unique=True, verbose_name='Product Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_avg_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Среднопретегелна себестойност', max_digits=10, verbose_name='Current Average Cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_stock_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Общо количество във всички складове', max_digits=12, verbose_name='Current Stock Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Цена от последната покупка', max_digits=10, null=True, verbose_name='Last Purchase Cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_purchase_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Purchase Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='track_batches',
            field=models.BooleanField(default=False, help_text='Проследяване на партиди/лотове', verbose_name='Track Batches'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('PIECE', 'Piece/Count'), ('WEIGHT', 'Weight (kg, g)'), ('VOLUME', 'Volume (l, ml)'), ('LENGTH', 'Length (m, cm)')], default='PIECE', help_text='Как се мери/продава този продукт', max_length=10, verbose_name='Unit Type'),
        ),
        migrations.AlterField(
            model_name='productbarcode',
            name='barcode',
            field=models.CharField(help_text='EAN13, UPC или вътрешен баркод', max_length=50, unique=True, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='productbarcode',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Основен баркод за този продукт', verbose_name='Is Primary'),
        ),
        migrations.AlterField(
            model_name='productbarcode',
            name='packaging',
            field=models.ForeignKey(blank=True, help_text='За коя опаковка е този баркод', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productpackaging', verbose_name='Packaging'),
        ),
        migrations.AlterField(
            model_name='productpackaging',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=3, help_text='Колко base_unit има в тази опаковка', max_digits=10, verbose_name='Conversion Factor'),
        ),
        migrations.AlterField(
            model_name='productpackaging',
            name='is_default_purchase_unit',
            field=models.BooleanField(default=False, help_text='Основна единица за покупка', verbose_name='Default Purchase Unit'),
        ),
        migrations.AlterField(
            model_name='productpackaging',
            name='is_default_sale_unit',
            field=models.BooleanField(default=False, help_text='Основна единица за продажба', verbose_name='Default Sale Unit'),
        ),
        migrations.AlterField(
            model_name='productpackaging',
            name='unit',
            field=models.ForeignKey(help_text='Мерна единица за тази опаковка', on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.unitofmeasure', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='productplu',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Основен PLU код за този продукт', verbose_name='Is Primary'),
        ),
        migrations.AlterField(
            model_name='productplu',
            name='plu_code',
            field=models.CharField(help_text='PLU код за везни продукти', max_length=10, verbose_name='PLU Code'),
        ),
        migrations.AlterField(
            model_name='productplu',
            name='priority',
            field=models.IntegerField(default=0, help_text='По-висок приоритет = предпочитан при конфликти', verbose_name='Priority'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='ProductGroup',
        ),
    ]
