# Generated by Django 5.2.3 on 2025-08-08 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='current_avg_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='current_stock_qty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_purchase_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_purchase_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_sale_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_sale_price',
        ),
        migrations.AddField(
            model_name='productpackaging',
            name='allow_purchase',
            field=models.BooleanField(default=True, help_text='Can be used for purchasing', verbose_name='Allow Purchase'),
        ),
        migrations.AddField(
            model_name='productpackaging',
            name='allow_sale',
            field=models.BooleanField(default=True, help_text='Can be used for selling', verbose_name='Allow Sale'),
        ),
        migrations.AddField(
            model_name='productpackaging',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Height (cm)'),
        ),
        migrations.AddField(
            model_name='productpackaging',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Length (cm)'),
        ),
        migrations.AddField(
            model_name='productpackaging',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='productpackaging',
            name='volume_m3',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Volume of packaging in cubic meters', max_digits=8, null=True, verbose_name='Volume (m³)'),
        ),
        migrations.AddField(
            model_name='productpackaging',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Width (cm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lifecycle_status',
            field=models.CharField(choices=[('NEW', 'New Product'), ('ACTIVE', 'Active'), ('PHASE_OUT', 'Phasing Out'), ('DISCONTINUED', 'Discontinued'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', help_text='Current product lifecycle stage', max_length=20, verbose_name='Lifecycle Status'),
        ),
        migrations.AlterField(
            model_name='productbarcode',
            name='barcode',
            field=models.CharField(db_index=True, help_text='Barcode value (EAN-13, EAN-8, etc.)', max_length=30, unique=True, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='productpackaging',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=3, help_text='How many base units in one packaging unit', max_digits=10, verbose_name='Conversion Factor'),
        ),
        migrations.AlterField(
            model_name='productpackaging',
            name='is_default_purchase_unit',
            field=models.BooleanField(default=False, help_text='Default unit for purchases', verbose_name='Default Purchase Unit'),
        ),
        migrations.AlterField(
            model_name='productpackaging',
            name='is_default_sale_unit',
            field=models.BooleanField(default=False, help_text='Default unit for sales', verbose_name='Default Sale Unit'),
        ),
        migrations.AlterField(
            model_name='productpackaging',
            name='unit',
            field=models.ForeignKey(help_text='Unit for this packaging (e.g., Box, Pallet)', on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.unitofmeasure', verbose_name='Packaging Unit'),
        ),
        migrations.AlterField(
            model_name='productpackaging',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Weight of packaging in kilograms', max_digits=8, null=True, verbose_name='Weight (kg)'),
        ),
    ]
