# Generated by Django 5.2.3 on 2025-07-10 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='primary_plu',
        ),
    ]
